"""Generate the project's instruction files and skills from the LIVE tool registry. Everything is deterministic: the tool skills quote each tool's own description and schema, the laws are assembled only
from sentences that exist in committed files (each carries its file:line, found by search so a wrong claim fails), and a registry hash in every generated file's marker lets `check` say 'stale' and name
the tools that were added or removed. A generated file whose marker the user removed is the user's and is never regenerated over."""
from __future__ import annotations

import ast
import hashlib
import json
import re
from pathlib import Path
from typing import Optional

from . import mirror as MIR

REPO = Path(__file__).resolve().parents[3]
MARK = "<!-- generated by lampway_agent_files from {h}; edits are overwritten: change the source -->"
MARK_RE = re.compile(r"<!-- generated by lampway_agent_files from ([0-9a-f]{8,64});")
AREAS = (("mesh", ("retopo", "uv_", "segment", "mesh_", "scene_", "batch_", "weight", "garment", "fit_", "auto_rig", "bind_", "rig_", "pose_", "skeleton")),
         ("material", ("procedural", "layered", "material", "bake", "pbr", "palette", "texture", "meshpaint", "detail", "ai_", "repair")),
         ("anim", ("anim", "clip_", "camera", "render_video", "video", "motion")),
         ("qa", ("qa_", "rebuild", "job_", "status")),
         ("pipeline", ("workflow", "armor", "asset", "ledger", "seed", "plate", "parts_", "proportion", "silhouette", "image", "prompt", "studio", "export_", "view_", "model_")),
         )
EXCLUDE = (("studio_", "spends credits on the owner's subscription: not offered to external agents (mcp.py)"), ("swarm_", "needs the agent loop (mcp.py)"), ("ask_user", "needs the agent loop (mcp.py)"))
LAW_PHRASES = (
    ("server/lampway_server/agent/prompt.py", "Never delete or overwrite the user's source files; the tools write new files."),
    ("server/lampway_server/agent/prompt.py", "Never run a tool that generates, uploads or spends credits unless the user asked for exactly that."),
    ("server/lampway_server/agent/prompt.py", "A proposal is never a ruling - only the user's tags or typed answers are."),
    ("server/lampway_server/agent/prompt.py", "When the request leaves a real choice open"),
    ("server/lampway_server/agent/prompt.py", "The sandbox has no file system access beyond a temp directory"),
    ("server/lampway_server/studios/approvals.py", "only the user can confirm a spend, from the Client; an agent or a worker never can"),
    ("server/lampway_server/spendpolicy.py", "it never lets anyone but the user click"),
    ("server/lampway_server/jobreceipts.py", "Nothing resubmits an unknown job"),
)


class LawError(ValueError):
    pass


def find_sentence(file: str, phrase: str):
    """(phrase, 'file:line') where the phrase starts on that line of that committed file, or LawError."""
    lines = (REPO / file).read_text().splitlines()
    for i, l in enumerate(lines, 1):
        if phrase in l or phrase.replace("`", "") in l.replace("`", ""):
            return phrase, f"{file}:{i}"
    raise LawError(f"the sentence {phrase!r} is not in {file}")


def laws() -> list:
    return [find_sentence(f, p) for f, p in LAW_PHRASES]


def registry() -> list:
    from ..agent.tools import TOOLS
    from ..mcp import offered_tools
    offered = {t.name for t in offered_tools()}
    rows = []
    for t in sorted(TOOLS, key=lambda x: x.name):
        sch = t.parameters or {}
        req = set(sch.get("required") or [])
        params = [{"name": k, "type": v.get("type", "string") if isinstance(v, dict) else "string", "desc": (v.get("description", "") if isinstance(v, dict) else ""), "required": k in req}
                  for k, v in (sch.get("properties") or {}).items()]
        rows.append({"name": t.name, "description": t.description, "params": params, "offered": t.name in offered})
    return rows


def registry_hash(rows) -> str:
    return hashlib.sha256(json.dumps([[r["name"], r["description"], r["params"]] for r in rows if r.get("offered")], sort_keys=True).encode()).hexdigest()[:16]


def area_of(name: str) -> str:
    n = name[len("lampway_"):] if name.startswith("lampway_") else name
    for area, prefixes in AREAS:
        if any(n.startswith(p) for p in prefixes):
            return area
    return "misc"


def exclusion(name: str) -> Optional[str]:
    for pre, why in EXCLUDE:
        if name.startswith(pre):
            return why
    return None


def _split(rows):
    inc, exc = [], []
    for r in rows:
        why = exclusion(r["name"]) or (None if r.get("offered") else "a server-run tool that needs the agent loop's server context: not offered over MCP")
        (exc if why else inc).append((r, why))
    return [r for r, _ in inc], [{"tool": r["name"], "reason": w} for r, w in exc]


def _front(name, desc):
    return f"---\nname: {name}\ndescription: {desc}\n---\n"


def _tool_md(r) -> str:
    lines = [f"### {r['name']}", "", r["description"].strip(), ""]
    if r["params"]:
        lines.append("Inputs:")
        for p in r["params"]:
            lines.append(f"- `{p['name']}` ({p['type']}{', required' if p['required'] else ''}){': ' + p['desc'] if p['desc'] else ''}")
        lines.append("")
    return "\n".join(lines)


def _steps():
    f = REPO / "src/scripts/mixar/modules/lampway_tools/pipeline/armor_piece.py"
    try:
        tree = ast.parse(f.read_text())
        for n in tree.body:
            if isinstance(n, ast.Assign) and any(getattr(t, "id", "") == "STEPS" for t in n.targets):
                return ast.literal_eval(n.value)
    except (OSError, SyntaxError, ValueError):
        pass
    return None


def render_all(rows=None) -> dict:
    rows = rows if rows is not None else registry()
    inc, exc = _split(rows)
    h = registry_hash(rows)
    out, covered = {}, {}
    lw = laws()
    law_text = "\n".join(f"- {s} (source: `{src}`)" for s, src in lw)
    lh = hashlib.sha256(law_text.encode()).hexdigest()[:16]
    out[".agents/skills/lampway-laws/SKILL.md"] = _front("lampway-laws", "The laws every agent working on a Lampway project follows: no source overwrites, no spends without the user, plan and ask rather than guess.") + \
        MARK.format(h=lh) + "\n\n# Lampway laws\n\nEach sentence below exists in a committed file; its source is cited.\n\n" + law_text + "\n"
    by = {}
    for r in inc:
        by.setdefault(area_of(r["name"]), []).append(r)
    for area, rs in sorted(by.items()):
        name = f"lampway-tools-{area}"
        body = "\n".join(_tool_md(r) for r in rs)
        out[f".agents/skills/{name}/SKILL.md"] = _front(name, f"How to use Lampway's {area} tools: each tool's purpose, inputs and refusals, quoted from the live registry.") + MARK.format(h=h) + f"\n\n# Lampway {area} tools\n\n" + body
        covered[name] = [r["name"] for r in rs]
    steps = _steps()
    if steps:
        rows_md = "\n".join(f"{n}. **{name}**: `{tool}`" + (f" ({credits} credits: always the user's click)" if kind == "spend" else "") + (" (a geometry step: texture goes stale)" if geo else "") for n, name, tool, credits, geo, kind in steps)
        rh = hashlib.sha256(json.dumps(steps).encode()).hexdigest()[:16]
        out[".agents/skills/lampway-runbook-armour/SKILL.md"] = _front("lampway-runbook-armour", "The armour piece runbook: 15 ordered steps from plates to an engine-ready export, with the order laws (texturing last).") + \
            MARK.format(h=rh) + "\n\n# Armour piece runbook\n\n" + rows_md + "\n\nTexturing comes last: every geometry or UV step runs on the pre-texture copy; a geometry step after the texture makes the texture stale.\n"
    index = "\n".join(f"- `lampway-tools-{a}`: {', '.join(r['name'] for r in rs[:6])}{' ...' if len(rs) > 6 else ''}" for a, rs in sorted(by.items()))
    out["AGENTS.md"] = MARK.format(h=h) + "\n\n# Agent instructions for this Lampway project\n\n## Laws\n\n" + law_text + \
        "\n\n## Where things are\n\n- Skills: `.agents/skills` (Claude's copy: `.claude/skills`). Load `lampway-laws` first.\n- Notes you keep: `knowledge/`, `processes/`, `context/`, `projects/`.\n- Personal preferences: `context/preferences.md` (the user's, not invented).\n\n## Tool skills\n\n" + index + "\n"
    out["CLAUDE.md"] = MARK.format(h=h) + "\n\n# Claude\n\nThe instructions for this project are in `AGENTS.md`: read it first.\n"
    return {"files": out, "covered": covered, "excluded": exc, "hash": h, "rows": rows, "included": [r["name"] for r in inc]}


def _marker_hash(text: str):
    m = MARK_RE.search("\n".join(text.splitlines()[:8]))
    return m.group(1) if m else None


def generate(root, rows=None, clients=("claude", "codex"), overwrite=False) -> dict:
    root = Path(root)
    ra = render_all(rows)
    written, skipped = [], []
    for rel, text in ra["files"].items():
        f = root / rel
        if f.exists():
            cur = f.read_text()
            if cur == text:
                continue
            if _marker_hash(cur) is None and not overwrite:
                skipped.append(rel)
                continue
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text)
        written.append(rel)
    if "claude" in clients:
        MIR.sync(root)
    skills = [{"name": n, "path": f".agents/skills/{n}/SKILL.md", "tools_covered": t} for n, t in sorted(ra["covered"].items())]
    skills += [{"name": "lampway-laws", "path": ".agents/skills/lampway-laws/SKILL.md", "tools_covered": []}]
    names = {t for s in skills for t in s["tools_covered"]}
    uncovered = sorted(set(ra["included"]) - names)
    return {"ok": True, "written": written, "skipped_user_owned": skipped, "skills": skills, "uncovered_tools": uncovered, "excluded": ra["excluded"], "registry_hash": ra["hash"]}


def _listed_tools(text: str) -> set:
    return set(re.findall(r"^### (\S+)$", text, re.M))


def check(root, rows=None) -> dict:
    root = Path(root)
    ra = render_all(rows)
    stale, problems = [], []
    expected_tools = set(ra["included"])
    for rel, text in ra["files"].items():
        f = root / rel
        if not f.exists():
            stale.append({"file": rel, "why": "missing"})
            continue
        cur = f.read_text()
        if cur == text:
            continue
        if _marker_hash(cur) is None:
            problems.append({"file": rel, "state": "differs-user-owned"})
            continue
        listed = _listed_tools(cur)
        want = _listed_tools(text)
        stale.append({"file": rel, "why": "stale", "tools_added": sorted(want - listed), "tools_removed": sorted(listed - want)})
    mir = MIR.check(root)
    ok = not stale and mir["ok"]
    return {"ok": ok, "stale": stale, "user_owned": problems, "mirror": mir, "registry_hash": ra["hash"], "message": "" if ok else "run action=generate (then sync) to refresh the skills from the registry"}


def mcp_instructions() -> str:
    lines = ["Lampway's tools for the open Blender scene."]
    lines += [f"- {s}" for s, _ in laws()[:6]]
    lines += ["- Agents can plan, never confirm a spend: only the user confirms, from the Client.", "Project instructions: AGENTS.md in the project root"]
    text = "\n".join(lines)
    while len(text.encode()) > 2048 and len(lines) > 3:
        lines.pop(-3)
        text = "\n".join(lines)
    return text
