"""The Wave 6 Lampway tool definitions that run in Blender (one api.call each, the same door as lampway_tools.DEFS). Kept apart from lampway_tools.py so
that file stays reviewable; lampway_tools appends these to DEFS, so BY_NAME, SPECS and the MCP offer see them like any other Def.

Each description is the api_wave6 function's docstring, word for word (GENERATED by scripts/lampway/gen_wave6_defs.py and pinned by tests/lampway_tools/test_wave6_door.py):
change the docstring and regenerate, never one side alone."""

from .tool_defs import Def, P

_PATHS = " Paths are relative to the project root; a path outside it is refused."
_OBJ = {"type": "object"}

DEFS = [
    Def("lampway_modular_character", "A character's interchangeable parts as one typed record. manifest {character_id, parts: [{object, role: head|body|hands|hair|garment|accessory, "
        "fixed_or_deforming, wearer_side: left|right|center|paired, bone (required for a fixed part)}], armature, allowed_outfits: [[part ids]], poses: rest | "
        "wiki8 | [poses]} writes <root>/<character_id>/manifest.json with the template fields. validate: one shared armature (two armatures are refused), the "
        "rest pose unchanged since the manifest, equal scales, each part's measured side against its declared one (the figure faces -Y, its left is +X), and "
        "weight_audit on every deforming part. outfit_matrix: per allowed outfit (in each pose) the body faces it leaves uncovered of the region any outfit "
        "covers (a ray from each face along its normal) and the body vertices poking through it; pass = both zero. hidden_body makes `<body>_hidden`, a copy "
        "without the faces every outfit covers, and is refused before a passing matrix or after anything changed since it. export_parts writes one FBX per part "
        "with the same armature under out_dir/<character_id>/. The full body is never deleted." + _PATHS,
        [P("action", desc="manifest | validate | outfit_matrix | hidden_body | export_parts", required=True),
         P("character_id", required=True),
         P("parts", "array", "manifest: [{object, role, fixed_or_deforming, wearer_side, bone}]", items=_OBJ),
         P("armature"),
         P("allowed_outfits", "array", "[[part ids]]", items={"type": "array", "items": {"type": "string"}}),
         P("poses", "string", "rest | wiki8 (default: the manifest's)"),
         P("out_dir")], api="modular_character"),
    Def("lampway_character_pipeline", "The character route as thirteen gated stages: 1 reference pack, 2 generate parts (tripo.mesh, a spend), 3 prep and segment, 4 assemble (fit), 5 "
        "retopology to the part budgets, 6 UV, 7 bake, 8 projection texture (a spend), 9 auto rig, 10 weights, 11 secondary chains, 12 skeleton check and "
        "export, 13 retarget test. parts: [{name, budget (triangles), rigid_bone}]. mode plan lists the stages with their tools (missing_tools = not built "
        "yet), spend flags, credits and state. mode record {stage, gate: pass|fail, evidence} appends a gate; a stage needs the stage before it passed, and "
        "rigging (9-11) needs the assembly (4) passed: \"fit before rigging\". mode run executes stage_calls {\"<n>\": [{tool, args}]} for "
        "from_stage..to_stage, each a tool of that stage, and stops at the first failed gate, the first spend stage (needs_approval: the user's click confirms "
        "spends, never this tool) and a stage whose tools are not built. target metahuman adds the MetaHuman conform as a needs_decision UE leg. Run record: "
        "<root>/<character_id>/pipeline/run.json.",
        [P("character_id", required=True),
         P("parts", "array", "[{name, budget, rigid_bone}]", required=True, items=_OBJ),
         P("mode", desc="plan | record | run"),
         P("target", desc="unreal_mannequin | metahuman | mixamo | vrm"),
         P("from_stage", "integer"),
         P("to_stage", "integer"),
         P("stage", "integer"),
         P("gate", desc="pass | fail"),
         P("evidence"),
         P("stage_calls", "object", "{\"<n>\": [{tool, args}]}")], api="character_pipeline"),
    Def("lampway_playblast_capture", "Light-engine playblasts of the posed blockout, one per shot, for the video model and the framing review. shots: [{name, camera: a camera object's name "
        "or waypoints [{frame, location}], frames: [first, last], duration_s (the planned video length of this shot), look_at: object name or [x, y, z] "
        "(waypoint cameras)}]. Each shot renders frames first..last of YOUR scene (its animation plays; the scene is linked, never edited) to "
        "out_dir/<name>.mp4 (H.264) plus <name>_first.png and <name>_last.png (stills: first | last | both | none), and out_dir/shot_list.json lists every file "
        "with its sha256. Refused: a shot whose length differs from its duration_s (or target_duration_s) by more than one frame (\"playblast length must match "
        "the planned video duration\"), Cycles (workbench | eevee only), an unknown camera, a hidden object named in scene_objects, duplicate shot names, more "
        "than 1200 frames. The temporary scene and waypoint cameras are removed and your frame is restored." + _PATHS,
        [P("shots", "array", "[{name, camera, frames: [a, b], duration_s, look_at}]", required=True, items=_OBJ),
         P("out_dir"),
         P("fps", "integer"),
         P("width", "integer"),
         P("height", "integer"),
         P("engine", desc="workbench | eevee"),
         P("stills", desc="first | last | both | none"),
         P("target_duration_s", "number"),
         P("scene_objects", "array", "objects that must be visible")], api="playblast_capture"),
    Def("lampway_lod_chain", "LOD copies of a mesh by collapse decimation, each measured. ratios: the fraction of faces each LOD keeps, 0.05..0.9 and strictly decreasing (default "
        "[0.5, 0.25, 0.1]); protect: a vertex group whose vertices are never collapsed (joints, rims, an emblem); preserve_uv_seams (default true) also keeps "
        "every vertex where the UV layout splits. Per LOD (`<name>_LOD<n>`, a new object; the source is untouched; a re-run replaces this tool's own LODs): "
        "faces, max_deviation_rel (the symmetric vertex-to-surface distance over the source's bounding diagonal), silhouette_iou (front and left, the smaller), "
        "weight_audit_pass (skinned meshes; null otherwise) and `textures` downsized by texture_scale (one per ratio, default halving) to "
        "out_dir/<stem>_LOD<n>.png (materials are not rewired). Refused: ratios not strictly decreasing or outside 0.05..0.9, a texture_scale list of another "
        "length, a skinned mesh without `protect` (\"protect the joint loops or run weight_audit after\"). The engine import is the user's check." + _PATHS,
        [P("object", required=True),
         P("ratios", "array", items={"type": "number"}),
         P("protect", desc="vertex group never collapsed"),
         P("texture_scale", "array", items={"type": "number"}),
         P("textures", "array", "texture files to downsize per LOD"),
         P("naming", desc="default {name}_LOD{n}"),
         P("preserve_uv_seams", "boolean"),
         P("out_dir")], api="lod_chain"),
    Def("lampway_motion_experiment", "The wiki's A/B/C motion comparison from a typed brief. brief: {duration_s 0.5..10, start, end (poses: {bones: [{bone, rotate: [x, y, z] degrees]}}, "
        "{bone: [x, y, z]} or a named pose: rest or a wiki8 pose), contact: {time_s, landmark, pose (optional)}, action, weapon_hand: left|right|null, "
        "preserve: [grip, foot_contact]}. variants: {A: keyed (made here: start at frame 1, the contact pose at its time, the end at the duration, the default "
        "interpolation; the landmark is a pose marker; action `<armature>_motion_A`, replaced on a re-run), B and C: the names of actions imported from an "
        "external tool}. B and C must start and end on the brief's poses (every named bone within 0.5 degrees) or the call is refused. Returns per variant the "
        "action and its measured audit (frames, duration, start/end/contact pose error, the largest bone angular speed and acceleration), the comparison table, "
        "and grade.smoothest (a measurement; a person picks). seed is not_exposed. Refused: a missing start or end pose (\"explicit start and end poses are "
        "required\"), foot_contact without a contact landmark, an unknown bone or action.",
        [P("brief", "object", "{duration_s, start, end, contact: {time_s, landmark, pose}, action, weapon_hand, preserve}", required=True),
         P("armature", required=True),
         P("variants", "object", "{A: keyed, B: action name, C: action name}")], api="motion_experiment"),
    Def("lampway_secondary_chain_rig", "A bone chain for a tail, hair, cape or coat under an existing bone, on COPIES (`<armature>_chain`, `<object>_chain`; the originals are kept; a re-run "
        "replaces this tool's copies). region: the geometry the chain drives, a world bounding box [[x, y, z], [x, y, z]] or a vertex group. The chain (bones "
        "2..24, named <naming>01..) runs along the region's principal axis from the end nearer parent_bone outward, connected, its first bone a child of "
        "parent_bone. The region's vertices are weighted to the chain and the parent only (every other influence is removed and counted); preview_constraint "
        "damped_track chains DAMPED_TRACK constraints for posing; colliders adds a capsule proxy per body bone (radius = its farthest vertex from the bone, "
        "parented to it). No numeric physics presets are emitted: masses, damping and limits are tuned per appendage in the engine. Refused: more than 24 bones "
        "(\"split into several chains\"), an unknown parent_bone (the bones are listed), a region with under 4 vertices, a base rig that fails weight_audit.",
        [P("object", required=True),
         P("armature", required=True),
         P("parent_bone", required=True),
         P("bones", "integer", "2..24, default 4"),
         P("naming", desc="tail_ | cape_ | hair_ ..."),
         P("region", "array", "[[x, y, z], [x, y, z]] world bounding box", items={"type": "array"}),
         P("preview_constraint", desc="damped_track | none"),
         P("colliders", "boolean")], api="secondary_chain_rig"),
    Def("lampway_cloth_garment_sim", "Drape a COPY of a garment (`<garment>_draped`) on a posed body with Blender cloth: pin_group (a vertex group) stays at its place, the body collides (a "
        "Collision modifier for the bake only), thickness_m 0.0005..0.02; frames 10..250 and a wall-clock budget bound the bake. The last frame becomes a "
        "static mesh (no cloth modifier, no cache left) and, with max_distance_map, the vertex group `max_distance` holds the engine-cloth map: 0 at the pins, "
        "rising with the distance to the nearest pin to 1 at max_distance_m. Returns the draped object and stats (max displacement, body penetrations, frames "
        "simulated). Refused: a metal garment (material_class metal or the object's lw_material_class: \"metal parts are not cloth: rigid or segmented "
        "binding\"), a garment with an Armature modifier (bind after the drape), an empty or missing pin group. Every numeric default is a placeholder: the "
        "sources give no usable numbers.",
        [P("garment", required=True),
         P("body", required=True),
         P("pin_group", required=True),
         P("frames", "integer", "10..250"),
         P("thickness_m", "number"),
         P("max_distance_map", "boolean"),
         P("max_distance_m", "number"),
         P("material_class", desc="metal is refused")], api="cloth_garment_sim"),
    Def("lampway_face_rig_validate", "Check a face rig by measurement. keys: the head's shape keys against the ARKit 52 (arkit) or ARKit + 15 visemes (arkit+visemes): present, missing, "
        "extra. interior: separate teeth and tongue objects and an open mouth at neutral. expressions: the wiki's six (neutral_blink, asymmetric_brow, "
        "wide_mouth, lips_together, teeth_tongue_clearance, speech_line), each set on the shape keys and MEASURED on the evaluated mesh from the vertex groups "
        "lip_upper, lip_lower, brow_l, brow_r (lip gap, brow asymmetry) and the teeth surface (the smallest signed lip-to-teeth distance; negative = "
        "penetrating); poses [{name, keys: {key: value}}] replaces the six. Every shape value is restored. profile vrm reports the VRM expression bindings as "
        "not checked unless the VRM add-on's data is present. Refused: no shape keys (\"generate them first (Faceit or manual)\"), teeth or tongue given on a "
        "closed mouth (\"open-mouth source needed or accept no interior check\"). Thresholds are proposals.",
        [P("object", required=True),
         P("shape_key_profile", desc="arkit | arkit+visemes | none"),
         P("teeth"),
         P("tongue"),
         P("profile", desc="generic | vrm"),
         P("poses", "array", "[{name, keys: {key: value}}]", items=_OBJ)], api="face_rig_validate"),
    Def("lampway_glb_optimize", "A lighter GLB for web preview, with the proof it still holds the same asset: Blender's glTF add-on re-writes the GLB with Draco mesh compression (or "
        "none), its images downsized to texture_px (the longest side) and as WebP at webp_quality 1..100, the animations kept unless keep_animation is false. "
        "The output is re-imported and compared: vertex_deviation_rel (the farthest input vertex from the output surface over the bounding diagonal), "
        "texture_ssim (the input's first image downsized the same way against the output's), the animations (count, frame ranges, animated positions); bytes "
        "before and after. Your scene is untouched (everything imported is removed). Refused: out equal to the input, a path outside the root, meshopt (glTF "
        "Transform's, an external engine the captain may approve), webp_quality outside 1..100." + _PATHS,
        [P("glb", required=True),
         P("out", required=True),
         P("mesh_compression", desc="draco | none"),
         P("texture_px", "integer"),
         P("webp_quality", "integer", "1..100"),
         P("keep_animation", "boolean")], api="glb_optimize"),
    Def("lampway_traversal_check", "Sweep a player capsule along a route ([[x, y, z], ...]) over the meshes of a collection (the blockout or a collision proxy) and report each route "
        "point's state: ok, blocked (a step above max_step_m, or a wall at knee or mid height, or a passage narrower than the capsule), too_steep (the ground "
        "steeper than max_slope_deg), low_ceiling (headroom under capsule_height_m) or gap (no ground wider than jump_gap_m, or a far side higher than "
        "jump_height_m), with the detail and the blocked count; sightlines [{from, to}] say whether each straight line is clear. player is required: "
        "{capsule_radius_m, capsule_height_m, max_step_m, max_slope_deg, jump_height_m, jump_gap_m} (the project's values; none is built in). Read-only. "
        "Refused: a missing capsule value, an unknown collection, a route point outside the blockout's bounds.",
        [P("route", "array", "[[x, y, z], ...]", required=True, items={"type": "array"}),
         P("collection", required=True),
         P("player", "object", "{capsule_radius_m, capsule_height_m, max_step_m, max_slope_deg, jump_height_m, jump_gap_m}", required=True),
         P("sightlines", "array", "[{from, to}]", items=_OBJ)], api="traversal_check"),
    Def("lampway_level_blockout", "A primitive blockout at real gameplay scale before any art: layout {start, goal, route: [[x, y, z]], scale_anchor: {object: a primitive's name, "
        "length_m}} (the anchor turns layout units into metres; without it they are metres); primitives [{set: ground|route|obstacles|landmarks, kind: "
        "box|ramp|stair, size: [x, y, z], at: [x, y, z] (the centre), name}] go into the collections <name>_ground, _route, _obstacles, _landmarks under <name> "
        "(a stair's riser fits under the player's max_step), the route is the polyline <name>_route_path, three fixed cameras (top, from the start, from the "
        "goal), and traversal_check runs on the result. Nothing is deleted. Refused: no player dimensions (\"project dimensions are required: the capsule "
        "decides what is traversable\"), a scene not in metres (scale_to_measure first), an unknown set or kind, a blockout name in use.",
        [P("layout", "object", "{start, goal, route, scale_anchor: {object, length_m}}", required=True),
         P("player", "object", "the capsule values"),
         P("primitives", "array", "[{set, kind, size, at, name}]", items=_OBJ),
         P("views", "integer"),
         P("name")], api="level_blockout"),
    Def("lampway_part_budget_plan", "Check a character's parts against the CAPTAIN's budget table (none is built in). table: [{role, camera_distance_m: [min, max], max_tris, texture_px}]; "
        "parts: [{object, role, camera_distance_m}]. Per part: triangles (an n-gon counts n - 2), its budget, over_by, the largest texture its materials use "
        "against the budget, and pass. Read-only. Refused: no table (\"the budget table is the captain's: none is built in\"), a role not in the table, a "
        "distance no row of that role covers. Post-processing budgets only: Tripo generation runs at maximum polycount.",
        [P("table", "array", "[{role, camera_distance_m: [min, max], max_tris, texture_px}]", items=_OBJ),
         P("parts", "array", "[{object, role, camera_distance_m}]", items=_OBJ)], api="part_budget_plan"),
    Def("lampway_platform_budget_check", "Check an asset against a platform's documented limits from a dated data table: roblox_rigid (4k triangles, 2048 texture, one watertight mesh), "
        "roblox_layered (4k triangles, 2048 texture, at most 4 bone weights per vertex, inner and outer cages), ue_static (no documented limit in the sources: "
        "use custom), custom (limits {max_tris, max_texture_px, watertight, max_weights, retrieved}). Returns each check (value, limit, pass), the date the "
        "limits were read and stale (older than 90 days: re-read the documentation). Read-only. Refused: an unknown platform (the known ones are listed), "
        "custom without limits.",
        [P("object", required=True),
         P("platform", desc="roblox_rigid | roblox_layered | ue_static | custom", required=True),
         P("limits", "object", "custom limits")], api="platform_budget_check"),
    Def("lampway_print_check", "Printability, measured in millimetres (the scene's unit scale, or units_per_mm): manifold (open and non-manifold edges), self-intersections "
        "(overlapping faces that share no vertex), isolated triangles, thin walls (a ray inward from every face: the walls under min_wall_mm, the thinnest "
        "first), the overhang area fraction (faces facing down within 90 - overhang_deg of straight down, not those on the build plate), floating parts (shells "
        "beyond the first), the size and whether it fits printer_volume_mm. Read-only. Refused: no min_wall_mm (the printer's), overhang_deg outside 30..80.",
        [P("object", required=True),
         P("min_wall_mm", "number", "the printer's minimum wall"),
         P("overhang_deg", "number", "30..80"),
         P("units_per_mm", "number"),
         P("printer_volume_mm", "array", "[x, y, z]", items={"type": "number"})], api="print_check"),
    Def("lampway_print_prep", "A physical-print derivative, kept apart from the game asset: a COPY of `object` (and of each object in split, at the same scale) with modifiers "
        "applied, an optional shared `base` unioned by Blender's exact boolean, merged and re-normalled, decimated to max_faces, scaled so its height is "
        "target_height_mm (5..500) and written in millimetres as one STL per part under out_dir; print_check gates it. The copies are removed. Refused: no "
        "min_wall_mm (\"the wall limit is the printer's: give it\"), an object with an armature (\"print derivatives are static: pose it first and apply\"), an "
        "open shell after repair, walls thinner than min_wall_mm at that size: nothing is written then. No slicer, supports or curing." + _PATHS,
        [P("object", required=True),
         P("target_height_mm", "number", "5..500", required=True),
         P("min_wall_mm", "number"),
         P("base"),
         P("max_faces", "integer"),
         P("out_dir"),
         P("split", "array", "more part objects at the same scale")], api="print_prep"),
    Def("lampway_profile_revolve", "A watertight lathe object from a 2D side profile: profile [[r, z], ...] (2..64 points, r >= 0) in the XZ plane spun about Z in steps 8..256 over "
        "angle_deg 1..360; a full turn merges the seam and points on the axis weld into poles, so a profile that starts and ends on the axis closes into a "
        "solid; bevel_m 0..0.05 bevels the corner vertices first; normals point outward. Returns the object, faces, manifold, open_edges and bounds (a partial "
        "angle leaves the cut open and says so). Refused: a profile that crosses the axis (a negative radius), fewer than 2 or more than 64 points, steps or "
        "angle out of range.",
        [P("profile", "array", "[[r, z], ...]", required=True, items={"type": "array"}),
         P("steps", "integer"),
         P("angle_deg", "number"),
         P("bevel_m", "number"),
         P("name")], api="profile_revolve"),
    Def("lampway_splat_world_import", "A Gaussian-splat environment in the scene: action import reads an SPZ (through the Client's own SPZ decoder, written as a 3DGS PLY beside it) or a "
        "3DGS PLY into ONE point object with colour, opacity and radius attributes and a geometry-nodes view; a splat has no faces, so mesh tools refuse it. "
        "Generating a world (text or image to a splat) is the server's lampway_splat_world: a world-model job the user confirms." + _PATHS,
        [P("action", desc="import"),
         P("path", desc=".spz or 3DGS .ply", required=True),
         P("max_points", "integer"),
         P("name")], api="splat_world"),
    Def("lampway_splat_collision_proxy", "A separate, named collision mesh for an imported splat, because visually dense splats do not imply physics surfaces: points whose opacity is at least "
        "min_opacity (0..1) are binned into voxels of voxel_m (0.02..1.0); a voxel with min_density of them is solid; the surface between solid and empty "
        "voxels is voxel-remeshed (closed and manifold) into the collection <splat>_collision as <splat>_collision, or UCX_<splat> for Unreal (export_for_ue). "
        "Returns faces, manifold, bounds and the share of the splat's opacity mass inside it. The splat is untouched. Refused: an object that is not a splat "
        "(no splat_opacity), more than 50 million voxels (\"raise voxel_m\"), values out of range.",
        [P("object", required=True),
         P("voxel_m", "number"),
         P("min_opacity", "number"),
         P("min_density", "integer"),
         P("name"),
         P("export_for_ue", "boolean")], api="splat_collision_proxy"),
    Def("lampway_vehicle_wheel_rig", "Prepare a generated car's wheels for an engine vehicle template: wheels [{object, name: wheel_fl|wheel_fr|wheel_rl|wheel_rr}], axis x | y (the axle "
        "direction). Each wheel's centre and radius come from a least-squares circle fit to its rim ring across its thinnest axis; a COPY named after the wheel "
        "gets its origin at the centre and is parented to a bone of that name (in `armature` or a new `<body>_wheels`); the originals keep their origins. "
        "Returns per wheel the centre, radius, fit residual, axle direction and how far the original origin was from the centre, and whether the four axles are "
        "parallel (within 2 degrees). Handling, wheel physics and collision stay engine-side. Refused: not exactly the four names, unapplied rotation or scale, "
        "a rim fit residual above 5 % of the radius (\"this does not look like a wheel\").",
        [P("body", required=True),
         P("wheels", "array", "[{object, name}]", required=True, items=_OBJ),
         P("axis", desc="x | y"),
         P("armature")], api="vehicle_wheel_rig"),
    Def("lampway_editor_connection_receipt", "Prove which editor, version and project you are really connected to before mutating anything, as a typed receipt under receipts/. blender (here): the "
        "version, the open file (it must be a saved copy under the project root, else nothing changes), the scene, the objects, then TestConnectionCube made at "
        "`position`, removed with its mesh, and the object list compared with the one before. unity | godot: pass the facts your own MCP connection read "
        "(editor_version, connector_release, project_path, scene, read_tool, undo_outcome); they are validated and stored. unreal: needs_decision (the UE "
        "editor leg waits on the Blender-to-UE render parity exploration). Refused: disposable not true (\"the create-undo test runs in a disposable copy "
        "only\"), an unsaved or outside-the-root file, missing facts (\"not connected\")." + _PATHS,
        [P("editor", desc="blender | unity | godot | unreal"),
         P("disposable", "boolean", required=True),
         P("position", "array", "[x, y, z]", items={"type": "number"}),
         P("transport", desc="bridge | mcp_stdio | mcp_http | other"),
         P("release"),
         P("facts", "object", "unity/godot: what your MCP read")], api="editor_connection_receipt"),
    Def("lampway_terrain", "A Blender landscape backdrop (no erosion simulation, no sky, no real-world data import). heightfield {name, preset mountains|hills|canyon| "
        "desert|flat, size_m 20..500, resolution 32..1024 (default 256), height_m, detail, detail_scale, warp, seed}: a grid with a geometry-nodes heightfield "
        "(LW_Terrain) whose height range is height_m and whose parameters stay live. carve {channel: {polyline: [[x, y]], width_m, depth_m, bank_m} | basin: "
        "{centre, radius_m, depth_m}}: COMMITS the terrain to vertices (stage two) and lowers the channel or basin by its depth with a smooth bank; nothing "
        "beyond the bank moves. water {water_level_m}: a water plane. vegetation {biome riparian|grassland|meadow|forest, asset_objects, water_level_m, "
        "max_instances, seed}: instances above the water and off steep ground, never more than max_instances. from_image {heightmap, size_m, resolution, "
        "height_m}: the grid displaced by a blurred heightmap. Refused: resolution above 1024 (\"capped at 1024\"), vegetation spread over more than 200 m "
        "(\"60-120 m reads lush\"), a ground-level photo as a heightmap (\"give a top-down height reference\"), unknown actions." + _PATHS,
        [P("action", desc="heightfield | carve | water | vegetation | from_image", required=True),
         P("name"),
         P("preset"),
         P("size_m", "number"),
         P("resolution", "integer"),
         P("height_m", "number"),
         P("detail", "number"),
         P("detail_scale", "number"),
         P("warp", "number"),
         P("seed", "integer"),
         P("channel", "object"),
         P("basin", "object"),
         P("water_level_m", "number"),
         P("biome"),
         P("asset_objects", "array"),
         P("max_instances", "integer"),
         P("heightmap")], api="terrain"),
    Def("lampway_addon_read", "Read one file of a Blender add-on project the Client links (its add-on projects folder; by project id or name). Refused: a project outside that folder "
        "(\"works on projects inside that folder only\"; the linked projects are listed).",
        [P("project", required=True),
         P("path", required=True)], api="addon_read"),
    Def("lampway_addon_stage_patch", "Stage a patch to a linked add-on project: files [{path, content}] (content null deletes the file), a message, and expected_revision (the revision "
        "addon_read returned: a project that changed since is refused; omitted, the current revision). Nothing changes on disk: the Client's service checks and "
        "stores the proposal and returns its patch_id. Show the patch to the user; they approve it in the Client.",
        [P("project", required=True),
         P("files", "array", "[{path, content}]", required=True, items=_OBJ),
         P("message"),
         P("expected_revision")], api="addon_stage_patch"),
    Def("lampway_addon_commit", "Commit an approved patch: the Client's transactional commit (rolled back on failing checks), then its checks and install (installed says whether the "
        "add-on loaded). Refused unless the user approved that very patch in the Client (\"a patch is committed only after the captain approves it\"); an "
        "agent's claim of approval is not one.",
        [P("project", required=True),
         P("patch_id", required=True)], api="addon_commit"),
    Def("lampway_addon_rollback", "Roll a linked add-on project back past one committed transaction (`to`, the transaction id from addon_commit), refused when the files changed since "
        "(the Client's revision check).",
        [P("project", required=True),
         P("to", required=True),
         P("expected_revision")], api="addon_rollback"),
    Def("lampway_material_palette", "Named dominant AND accent colours from an image (alpha-aware: transparent pixels never count), deterministic: method notable (area colours plus vivid "
        "accents by hue family, each new colour at least 8 CIELAB units from the others) or kmeans (seeded, may merge a small accent); n 2..24; locked [{name, "
        "hex}] colours are kept as given. Each colour: name, hex, sRGB, linear, coverage (summing to 1) and kind (area | accent | locked). compare_to a second "
        "image: the palette distance in CIELAB (mean, max, p90, pairs) so colour drift has a number. Writes out_dir/<image>.palette.json and a swatch PNG; "
        "make_materials adds Principled materials PAL_<image>_<i> (never overwriting one). Refused: n out of range, more locked colours than n, an image "
        "outside the root or without opaque pixels, pms (Pantone needs licensed books Lampway does not have)." + _PATHS,
        [P("image", required=True),
         P("n", "integer"),
         P("locked", "array", "[{name, hex}]", items=_OBJ),
         P("method", desc="notable | kmeans"),
         P("alpha_min", "number"),
         P("max_pixels", "integer"),
         P("seed", "integer"),
         P("make_materials", "boolean"),
         P("compare_to"),
         P("out_dir"),
         P("pms", "boolean")], api="material_palette"),
    Def("lampway_scene_from_image", "One reference image to separate, editable objects placed as the image arranges them. engine pipeline: the image's parts (masks given, or found by "
        "segment_image by colour or alpha), each extruded from its own silhouette (image_to_3d), placed under an ASSUMED straight-on camera (the image is "
        "scene_width_m wide over a scene_depth_m deep ground plane; lower in the image is nearer; each part stands on the ground at its pixel height: an "
        "approximation), into the collection <name>_scene, left to right as in the image. engine studio:tripo: a plan only, the number of objects x the "
        "action's price with the total, one confirm for the whole scene; nothing is created. Refused: max_objects outside 1..16, more parts than max_objects, a "
        "model engine (reconstruction is never local), a scene name in use." + _PATHS,
        [P("image", required=True),
         P("masks", "array", "mask PNGs (white = the part)"),
         P("max_objects", "integer", "1..16"),
         P("name"),
         P("engine", desc="pipeline | studio:tripo"),
         P("scene_width_m", "number"),
         P("scene_depth_m", "number")], api="scene_from_image"),
    Def("lampway_motion_generate", "A motion clip for a short prompt. engine library (the default): a deterministic ranker over the clips indexed in <library>/index.json (the prompt's "
        "words against each clip's name and the captain's tags; ties go to the duration nearest `duration`); the picked clip is imported as the armature "
        "motion_src with its action named after the clip (replacing this tool's previous one), its frames and fps read back, and one decision row is appended "
        "to motion/decisions.jsonl. action index scans the library folder (fbx, glb, gltf, bvh) into index.json, keeping existing tags. engine model:kimodo | "
        "model:unimate: needs_provider (no text-to-motion host is configured; nothing is run or sent, and there is no silent fallback to the library). Refused: "
        "an empty or over-long prompt, duration outside 0.5..10, no clip matching (the library's words are listed), no index, a folder outside the root. Feed "
        "the clip to animation_retarget." + _PATHS,
        [P("prompt"),
         P("engine", desc="library | model:kimodo | model:unimate"),
         P("action", desc="generate | index"),
         P("library", desc="project folder of clips, default anims"),
         P("duration", "number", "0.5..10 s"),
         P("skeleton", desc="model engines only"),
         P("fps", "integer"),
         P("seed", "integer"),
         P("num_samples", "integer")], api="motion_generate"),
]
