# SPDX-FileCopyrightText: 2026 Lampway contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Ported from the owner's tool shelf (tools/libwiki/gen_parts_table.py, sha256 147f923c8ea9) on 2026-10-06. The header below, with the measured rules behind
# the code, is the original's; the usage lines name Lampway's script paths.
# SPIKE (2026-10-03): write a part set's table into the mesh wiki's entity spec FROM the exported files, never by hand
# (wiki critique round 2, C2-C2/C2-C10): one row per part of SET.<v>.json, read from that part's part.json - version,
# faces, motion class, the full bind, and the held notes keyed to the part (by their title, the text before the first
# colon; the full notes stay in part.json and on the entity's Open list). The table states the SET file and its sha256.
# 2026-10-04: the entity's Open list is generated too - every held note of SET.<v>.json in full with the parts it
# names ('*' = every part), so the list cannot drift from the set it describes.
# Usage: python3 gen_parts_table.py <entities.json> <slug> <set dir> <set_version>
# --- AXI prelude (tools/AXI.md): no args shows what this is; too few args or an unknown flag refuses on stdout (script runs only, never on import) ---
import sys as _sys, os as _os
_sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..')); import axi_out as _ax
_A = _sys.argv[1:]
_bad = [] if __name__ != '__main__' else [x for x in _A if x.startswith('--') and x.split('=')[0] not in []]
if _bad: print(f'error: unknown flag(s) {_bad}'); _ax.helps(['python3 scripts/libwiki/gen_parts_table.py <entities.json> <slug> <set dir> <set_version>']); _sys.stdout.flush(); raise SystemExit(2)
if __name__ == '__main__' and len(_A) < 4:
    if not _A: _ax.home(__file__, "Write a part set's table into the mesh wiki's entity spec from the exported files")
    else: print(f'error: {len(_A)} argument(s); at least 4 needed')
    _ax.helps(['python3 scripts/libwiki/gen_parts_table.py <entities.json> <slug> <set dir> <set_version>']); _sys.stdout.flush(); raise SystemExit(0 if not _A else 1)
# --- end AXI prelude ---
import hashlib, json, os, sys


def main(spec_path, slug, setdir, ver):
    spec = json.load(open(spec_path)); e = [x for x in spec['entities'] if x['slug'] == slug]
    if len(e) != 1: _ax.refuse(f'no single entity {slug!r}', ['python3 scripts/libwiki/gen_parts_table.py <entities.json> <slug> <set dir> <set_version>'])
    setf = os.path.join(setdir, f'SET.{ver}.json'); setj = json.load(open(setf))
    cell = lambda s: str(s).replace('|', '/').replace('\n', ' ')
    rows = []
    for p in sorted(setj['parts'], key=lambda x: x['part']):
        pj = json.load(open(os.path.join(setdir, p['part'], p['version'], 'part.json')))
        if (pj['part'], pj['faces']) != (p['part'], p['faces']): _ax.refuse(f'{p["part"]}: SET and part.json disagree', ['python3 scripts/partseg/verify_set.py <source.glb> <set dir> <set_version>'])
        held = '; '.join(cell(n.split(':')[0]) for n in pj['held_notes']) or '-'
        rows.append(f"| `{pj['part']}` | {p['version']} | {pj['faces']:,} | {cell(pj['motion_class'])} | {cell(pj['bind'])} | {held} |")
    sha = hashlib.sha256(open(setf, 'rb').read()).hexdigest()
    e[0]['table'] = ['## Part table', '',
                     f'Generated by `gen_parts_table.py` from `SET.{ver}.json` (sha256 `{sha}`) and each part\'s `part.json`; do not edit by hand. '
                     'Held notes are named by title; their full text is in each part.json and under Open below.', '',
                     '| part | version | faces | motion class | bind | held notes |', '|---|---|---|---|---|---|'] + rows
    held = setj.get('held', [])
    e[0]['open'] = [f'held notes (SET.{ver}.json, generated; each is carried into the part.json of every part it names):'] + [
        f"  {cell(h['note'])}  [parts: {'every part' if '*' in h['parts'] else ', '.join(h['parts'])}]" if isinstance(h, dict) else f'  {cell(h)}' for h in held]
    json.dump(spec, open(spec_path, 'w'), indent=1, ensure_ascii=False)
    print(f'{len(rows)} rows, faces {sum(p["faces"] for p in setj["parts"]):,}')


if __name__ == '__main__':
    main(*sys.argv[1:5])
