# SPDX-FileCopyrightText: 2026 Lampway contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""What the Asset Vault window says and paints, as pure functions (specs/client_facelift/09-asset-vault.md, DESIGN v2 sections 13-14): no bpy, so the words and the draw lists
are tested without Blender. The panels and the draw handler only render what these return."""

import re
import time

DATED = re.compile(r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}  ")
RELATION_WORDS = {"generated_from": "generated from", "derived_from": "derived from", "variant_of": "variant of", "part_of": "part of", "textured_by": "textured by",
                  "fits_body": "fits", "rigged_to": "rigged to", "drives": "drives", "uses": "uses", "frame_of": "frame of", "supersedes": "supersedes"}
PARENT_TYPES = ("generated_from", "derived_from", "variant_of", "part_of", "supersedes")


def _when(ts, tz=None) -> str:
    t = time.gmtime(ts + tz) if tz is not None else time.localtime(ts)
    return time.strftime("%Y-%m-%d %H:%M", t)


def similar_chip(backend: dict) -> dict:
    """Where "find similar" runs: the bundled model on this machine (the lamp, go) or a remote route (the wire, its host). Unknown means local: the server runs the bundled model."""
    if (backend or {}).get("location", "local") == "local":
        return {"glyph": "lamp", "colour": "go", "text": "local embeddings, no egress", "tooltip": "Similarity runs on this machine; nothing leaves it"}
    host = backend.get("host") or "a remote route"
    return {"glyph": "wire", "colour": "wire", "text": f"via {host}", "tooltip": f"Similarity sends data to {host}"}


def parents(rec: dict) -> list:
    return [r for r in rec.get("relations") or [] if r.get("src") == rec.get("id") and r.get("type") in PARENT_TYPES]


def provenance_lines(rec: dict, tz=None) -> list:
    """"Where it came from": every line starts with its date and time."""
    lines = []
    for g in rec.get("generation") or []:
        ts = g.get("finished_at") or g.get("started_at")
        if ts:
            what = " ".join(str(x) for x in (g.get("studio"), g.get("model"), g.get("action")) if x)
            lines.append(f"{_when(ts, tz)}  generated by {what}" + (f" (job {g['job_id']})" if g.get("job_id") else ""))
    if rec.get("created_at"):
        ps = parents(rec)
        tail = f", from {', '.join(RELATION_WORDS[p['type']] + ' ' + p['dst'] for p in ps)}" if ps else ""
        lines.append(f"{_when(rec['created_at'], tz)}  entered the Vault{tail}")
    return sorted(lines)


def provenance_glance(rec: dict, tz=None) -> str:
    """The collapsed form: "14:02, 2 parents"; the timeline is one click away."""
    n = len(parents(rec))
    hhmm = _when(rec.get("created_at") or 0, tz)[11:]
    return f"{hhmm}, {n} parent{'s' if n != 1 else ''}" if n else f"{hhmm}, no parents"


def tile_bed(rect, selected: bool, palette: dict) -> list:
    """The draw list under a thumbnail: the 3D view's pool of light, or the lamplit bed with an accent edge for the selected tile."""
    if selected:
        return [("radial", rect, palette["accent_bed_hi"], palette["accent_bed"]), ("edge", rect, palette["accent"])]
    return [("radial", rect, palette["viewport_hi"], palette["viewport_lo"])]


def _n(v) -> str:
    return f"{int(v):,}".replace(",", " ")


def _g(v) -> str:
    return f"{float(v):g}"


STATS = {
    "mesh": [("Triangles", lambda s: _n(s["tris"]), ("tris",)), ("Vertices", lambda s: _n(s["verts"]), ("verts",)),
             ("Size", lambda s: f"{_g(s['dim_x'])} x {_g(s['dim_y'])} x {_g(s['dim_z'])} m", ("dim_x", "dim_y", "dim_z")),
             ("Materials", lambda s: str(s["materials"]), ("materials",)), ("UV sets", lambda s: str(s["uv_sets"]), ("uv_sets",)),
             ("Watertight", lambda s: "yes" if s["watertight"] else "no", ("watertight",)), ("Bones", lambda s: str(s["bones"]), ("bones",))],
    "image": [("Pixels", lambda s: f"{s['width']} x {s['height']}", ("width", "height")), ("Colour space", lambda s: s["colorspace"], ("colorspace",)),
              ("Normal", lambda s: s["normal_convention"].upper(), ("normal_convention",))],
    "video": [("Motion fps", lambda s: f"{_g(s['motion_fps'])} (container {_g(s['container_fps'])})", ("motion_fps", "container_fps")),
              ("Frame", lambda s: f"{s['width']} x {s['height']}", ("width", "height")), ("Duration", lambda s: f"{_g(s['duration_s'])} s", ("duration_s",)),
              ("Duplicate frames", lambda s: str(s["dup_frames"]), ("dup_frames",))],
    "animation": [("Frames", lambda s: str(s["frames"]), ("frames",)), ("fps", lambda s: _g(s["fps"]), ("fps",)), ("Loops", lambda s: "yes" if s["loops"] else "no", ("loops",))],
    "rig": [("Bones", lambda s: str(s["bones"]), ("bones",)), ("Naming", lambda s: s["naming"], ("naming",))],
    "material": [("Shader", lambda s: s["shader"], ("shader",)), ("Role", lambda s: s["role"], ("role",))],
    "map": [("Channel", lambda s: s["channel"], ("channel",)), ("Convention", lambda s: s["convention"].upper(), ("convention",))],
}
STATS["hdri"] = STATS["image"]


def stats_rows(rec: dict) -> list:
    s = rec.get("stats") or {}
    return [(label, fmt(s)) for label, fmt, keys in STATS.get(rec.get("kind"), []) if all(s.get(k) is not None for k in keys)]
