#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Lampway contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Lampway's icons (facelift contract 14), rendered from one sheet: ``icons/lampway_icons.svg``.

    python3 scripts/dev/brand_art/lampway_icons.py            # write into the repo
    python3 scripts/dev/brand_art/lampway_icons.py --out DIR  # write the same tree under DIR

Writes:
* the native set, ``src/release/datafiles/icons_svg/lampway_<name>.svg`` (white strokes: Blender tints mono icons with
  the theme), and Generate redrawn as an image frame with a plus (``generate.svg``);
* the generated blocks of ``UI_icons.hh`` (``DEF_ICON(LAMPWAY_<NAME>)``) and of ``editors/datafiles/CMakeLists.txt``;
  the retired icons (sparkle, Mixar's credit badges) are removed from both;
* the previews for Python surfaces, ``src/scripts/mixar/modules/common/lampway_icons/<night|paper>/<name>.png``
  (32 px, the cue colour of DESIGN.md 13 baked per theme; the agent states also at 16 px), rasterised with ImageMagick's
  librsvg, the same SVG the build compiles;
* the acceptance sheet, ``docs/reports/facelift/icons_<night|paper>.png`` (every native icon at 16, 20 and 32 px).

The native set needs a native rebuild; the previews do not.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SHEET = Path(__file__).resolve().parent / "icons" / "lampway_icons.svg"
TOKENS = ROOT / "scripts/lampway/facelift/theme/tokens.json"
NS = "http://www.w3.org/2000/svg"
ICONS_SVG = "src/release/datafiles/icons_svg"
UI_ICONS = "src/source/blender/editors/include/UI_icons.hh"
CMAKE = "src/source/blender/editors/datafiles/CMakeLists.txt"
PREVIEWS = "src/scripts/mixar/modules/common/lampway_icons"
REPORT = "docs/reports/facelift"

NATIVE = ("lamp", "wire", "coin", "cap", "receipt", "route", "shield", "shield-half", "shield-open", "shield-q", "hand",
          "spark", "worker", "pane", "compare", "vault", "gate", "node-lit", "node-half", "node",
          *[f"meter-{n}" for n in range(11)], "meter-near", "meter-over", "wire-dot-a", "wire-dot-b",
          "agent-idle", "agent-working", "agent-unread", "agent-blocked", "agent-paused", "agent-done", "agent-failed")
RETIRED_ENUMS = ("SPARKLE", "CREDITS_UPGRADE", "CREDITS_SLIDE", "CREDITS_REFER", "CREDITS_CREATOR")
RETIRED_SVGS = ("sparkle", "credits_upgrade", "credits_slide", "credits_refer", "credits_creator")
# The colour each glyph means (DESIGN.md 13); everything else is plain text colour.
CUE = {"agent-idle": "line_hi", "agent-working": "accent", "agent-unread": "agent", "agent-blocked": "accent",
       "agent-paused": "muted_dim", "agent-done": "go", "agent-failed": "stop", "meter-near": "accent",
       "meter-over": "stop", "meter-9": "stop", "meter-10": "stop", "wire-dot-a": "wire", "wire-dot-b": "wire",
       "lamp": "muted_dim", "wire": "muted", "hand": "accent", "spark": "accent"}
CUE.update({f"meter-{n}": "accent_bed_hi" for n in range(9)})
# Preview-only glyphs (no native icon): the connection family of specs/connections/connections_face.md 5.3. Each is one or more
# layers (symbol, cue colour) composited in order, so the warning is a go dot with an accent triangle.
PREVIEW_ONLY = {"conn_connected": (("node-lit", "go"),), "conn_warning": (("node-lit", "go"), ("tri-small", "accent_text")),
                "conn_unchecked": (("node", "agent"),), "conn_signed_out": (("ring-open", "muted"),),
                "conn_expired": (("clock", "accent_text"),), "conn_missing": (("ring-dashed", "muted_dim"),),
                "conn_error": (("cross", "stop"),), "conn_waiting": (("hand", "accent"),), "plug": (("link", "muted"),),
                # the choice family of specs/choices/choices_face.md 5.3 (the waiting proposal reuses conn_waiting's hand), and the eye
                "choice_preferred": (("diamond", "go"),), "choice_fallback": (("diamond-half", "accent_text"),),
                "choice_override": (("diamond-dot", "agent"),), "choice_blocked": (("diamond-cross", "stop"),),
                "choice_unset": (("diamond-dashed", "muted_dim"),), "eye": (("eye", "muted"),)}
BEGIN_HH, END_HH = "/* Lampway icons: GENERATED by scripts/dev/brand_art/lampway_icons.py (contract 14). */", \
    "/* End of the Lampway icons. */"
BEGIN_CMAKE, END_CMAKE = "      # Lampway icons: GENERATED by scripts/dev/brand_art/lampway_icons.py (contract 14).", \
    "      # End of the Lampway icons."


def native_name(sid: str) -> str:
    return "shield_unknown" if sid == "shield-q" else sid.replace("-", "_")


def symbols() -> dict:
    return {s.get("id"): s for s in ET.parse(SHEET).getroot().iter(f"{{{NS}}}symbol")}


def _inner(symbol, colour: str) -> str:
    ET.register_namespace("", NS)
    parts = []
    for child in symbol:
        text = ET.tostring(child, encoding="unicode").replace(f' xmlns="{NS}"', "")
        parts.append(text.replace("currentColor", colour))
    return "".join(parts)


def native_svg(symbol, colour: str = "#ffffff") -> str:
    return ("<!-- SPDX-FileCopyrightText: 2026 Lampway contributors -->\n"
            "<!-- SPDX-License-Identifier: GPL-3.0-or-later -->\n"
            f"<!-- GENERATED by scripts/dev/brand_art/lampway_icons.py from icons/lampway_icons.svg#{symbol.get('id')}; "
            "edit the sheet, not this file. -->\n"
            '<svg width="1600" height="1600" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">\n'
            f'<g fill="none" stroke="{colour}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">'
            f"{_inner(symbol, colour)}</g>\n</svg>\n")


def ui_icons_hh(text: str) -> str:
    for enum in RETIRED_ENUMS:
        text = re.sub(rf"^DEF_ICON\w*\({enum}\)\n", "", text, flags=re.M)
    text = text.replace("/* Credit-exhaustion actions (keep existing icon identifiers stable). */\n", "")
    text = text.replace("DEF_ICON_COLOR(GENERATE)", "DEF_ICON(GENERATE)")  # redrawn mono: tinted by the theme
    block = "\n".join([BEGIN_HH, *(f"DEF_ICON(LAMPWAY_{native_name(s).upper()})" for s in NATIVE), END_HH]) + "\n\n"
    text = re.sub(re.escape(BEGIN_HH) + r".*?" + re.escape(END_HH) + r"\n\n", "", text, flags=re.S)
    # init_internal_icons() registers SVG icons only below DEF_ICON_BLANK(LAST_SVG_ITEM): the block goes just above it
    anchor = "/* The items above are initiated sequentially"
    if text.count(anchor) != 1:
        raise SystemExit(f"{UI_ICONS}: expected one '{anchor}'")
    return text.replace(anchor, block + anchor)


def cmake_list(text: str) -> str:
    for name in RETIRED_SVGS:
        text = re.sub(rf"^      {name}\n", "", text, flags=re.M)
    block = "\n".join([BEGIN_CMAKE, *(f"      lampway_{native_name(s)}" for s in NATIVE), END_CMAKE]) + "\n"
    if BEGIN_CMAKE in text:
        text = re.sub(re.escape(BEGIN_CMAKE) + r".*?" + re.escape(END_CMAKE) + r"\n", lambda _m: block, text, flags=re.S)
    else:
        anchor = "      mixar_icon\n"
        if text.count(anchor) != 1:
            raise SystemExit(f"{CMAKE}: expected one '{anchor.strip()}' line")
        text = text.replace(anchor, anchor + block)
    return text


def rasterise(svg_text: str, out: Path, size: int) -> None:
    if shutil.which("magick") is None:
        raise SystemExit("ImageMagick (magick, with librsvg) is needed to rasterise the previews")
    sized = svg_text.replace('width="1600" height="1600"', f'width="{size}" height="{size}"', 1)
    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as fh:
        fh.write(sized)
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["magick", "-background", "none", fh.name, "-strip", f"PNG32:{out}"], check=True)
    Path(fh.name).unlink()


def write(out: Path) -> list[str]:
    syms = symbols()
    missing = [s for s in (*NATIVE, "generate", *(sid for layers in PREVIEW_ONLY.values() for sid, _ in layers)) if s not in syms]
    if missing:
        raise SystemExit(f"the sheet lacks {missing}")
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))["colour"]
    written = []

    def put(rel: str, text: str) -> None:
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(rel)

    for sid in NATIVE:
        put(f"{ICONS_SVG}/lampway_{native_name(sid)}.svg", native_svg(syms[sid]))
    put(f"{ICONS_SVG}/generate.svg", native_svg(syms["generate"]))
    for rel in RETIRED_SVGS:
        retired = out / ICONS_SVG / f"{rel}.svg"
        if retired.exists():
            retired.unlink()
    put(UI_ICONS, ui_icons_hh((ROOT / UI_ICONS).read_text(encoding="utf-8")))
    put(CMAKE, cmake_list((ROOT / CMAKE).read_text(encoding="utf-8")))
    for theme, variant in (("night", "dark"), ("paper", "light")):
        for sid in NATIVE:
            colour = tokens[CUE.get(sid, "text")][variant]
            sizes = (16, 32) if sid.startswith("agent-") else (32,)
            for size in sizes:
                suffix = "" if size == 32 else f"_{size}"
                rasterise(native_svg(syms[sid], colour), out / PREVIEWS / theme / f"{native_name(sid)}{suffix}.png", size)
        for name, layers in PREVIEW_ONLY.items():
            _layers(syms, tokens, variant, layers, out / PREVIEWS / theme / f"{name}.png")
        _sheet(syms, tokens, variant, out / REPORT / f"icons_{theme}.png")
    return written


def _layers(syms, tokens, variant, layers, path: Path, size: int = 32) -> None:
    """One preview from layers of (symbol, cue colour), composited in order."""
    from PIL import Image
    with tempfile.TemporaryDirectory() as tmp:
        image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        for n, (sid, cue) in enumerate(layers):
            png = Path(tmp) / f"{n}.png"
            rasterise(native_svg(syms[sid], tokens[cue][variant]), png, size)
            image.alpha_composite(Image.open(png).convert("RGBA"))
        path.parent.mkdir(parents=True, exist_ok=True)
        image.save(path)


def _sheet(syms, tokens, variant, path: Path) -> None:
    """Every native icon at 16, 20 and 32 px on the theme's surface, one row per size."""
    from PIL import Image
    with tempfile.TemporaryDirectory() as tmp:
        cell, sizes = 40, (16, 20, 32)
        back = tokens["surface"][variant]
        sheet = Image.new("RGBA", (cell * len(NATIVE), cell * len(sizes)), back)
        for row, size in enumerate(sizes):
            for col, sid in enumerate(NATIVE):
                png = Path(tmp) / f"{sid}_{size}.png"
                rasterise(native_svg(syms[sid], tokens[CUE.get(sid, "text")][variant]), png, size)
                icon = Image.open(png).convert("RGBA")
                at = (col * cell + (cell - size) // 2, row * cell + (cell - size) // 2)
                sheet.alpha_composite(icon, at)
        path.parent.mkdir(parents=True, exist_ok=True)
        sheet.convert("RGB").save(path, optimize=True)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", type=Path, default=None, help="write the tree under this directory instead of the repo")
    args = ap.parse_args(argv)
    out = args.out or ROOT
    if args.out is not None:  # a fresh tree: the retired SVGs are simply never written
        (out / ICONS_SVG).mkdir(parents=True, exist_ok=True)
    written = write(out)
    print(f"lampway_icons: {len(NATIVE)} native icons, {len(written)} files written under {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
