"""The Lampway terminal (facelift contract 16): a pinned WezTerm release, downloaded on demand into $LAMPWAY_HOME and
launched as Lampway's own companion window.

Download: only through the egress gate's `github` route (refused before any request while it is off), streamed to a
.part file, its SHA-256 compared with the value pinned in `lampway_terminal.toml` AND with the release's published
.sha256; only then moved into place with WezTerm's licence and a PROVENANCE.json beside it.

Launch: `wezterm --config-file <Lampway's lua> start --always-new-process --class dev.lampway.terminal`, with Lampway's
own WEZTERM_UNIX_SOCKET and the isolated herdr environment, detached from Blender. It never reads, writes or includes the
user's WezTerm config, never addresses the user's WezTerm (every CLI call carries Lampway's class and socket), never
signals a process it did not start, and never sends text to a pane it did not create."""

import hashlib
import json
import os
import platform
import shutil
import signal
import subprocess
import tarfile
import tempfile
import time
import tomllib
import zipfile
from pathlib import Path
from typing import Callable, Optional

from .. import egress as E

HERE = Path(__file__).resolve().parent
PINS = HERE / "lampway_terminal.toml"
CONFIG = HERE / "lampway.wezterm.lua"          # generated by scripts/lampway/facelift/theme/build_theme.py
CLASS = "dev.lampway.terminal"
ROUTE = "github"


class TerminalRefused(RuntimeError):
    pass


def load_pins() -> dict:
    return tomllib.loads(PINS.read_text(encoding="utf-8"))


def platform_key() -> str:
    system, machine = platform.system().lower(), platform.machine().lower()
    arch = {"amd64": "x86_64", "x86_64": "x86_64", "aarch64": "arm64", "arm64": "arm64"}.get(machine, machine)
    if system == "darwin":
        return "macos"
    return f"{system}-{arch}"


def pin_for(key: str, pins: Optional[dict] = None) -> dict:
    pins = pins if pins is not None else load_pins()
    if key not in pins:
        raise TerminalRefused(f"no pinned WezTerm build for {key}: use the browser cockpit")
    return pins[key]


def _home(home) -> Path:
    if not home:
        raise TerminalRefused("start Lampway with its launcher; the terminal lives under LAMPWAY_HOME")
    return Path(home)


def _route_off() -> bool:
    return E.ACTIVE is not None and not E.ACTIVE.enabled(ROUTE)


def _fetch(client, url: str, out: Path) -> str:
    """Stream ``url`` into ``out``; return its SHA-256. Redirects are followed one hop at a time (at most five), so every
    hop passes the egress gate and the log names each host the bytes came from."""
    h = hashlib.sha256()
    for _hop in range(6):
        resp = client.send(client.build_request("GET", url), stream=True)
        try:
            if resp.is_redirect:
                url = str(resp.next_request.url) if resp.next_request is not None else resp.headers["location"]
                continue
            if resp.status_code >= 400:
                raise TerminalRefused(f"{url} answered HTTP {resp.status_code}: nothing was installed")
            with out.open("wb") as fh:
                for chunk in resp.iter_bytes():
                    h.update(chunk)
                    fh.write(chunk)
            return h.hexdigest()
        finally:
            resp.close()
    raise TerminalRefused(f"{url}: too many redirects; nothing was installed")


def write_config(home) -> Path:
    """Copy the generated config into $LAMPWAY_HOME/wezterm/ (and Plex Mono, when the repository's vendored copy is here)."""
    home = _home(home)
    dst = home / "wezterm" / "lampway.wezterm.lua"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(CONFIG, dst)
    # IBM Plex Mono as TrueType (WezTerm 20240203 cannot read woff2): generated by scripts/dev/brand_art/fonts_ttf.py, OFL beside it
    fdir = home / "addons" / "wezterm" / "fonts"
    fdir.mkdir(parents=True, exist_ok=True)
    for f in [*(HERE / "fonts").glob("*.ttf"), HERE / "fonts" / "OFL-IBM-Plex-Mono.txt"]:
        shutil.copyfile(f, fdir / f.name)
    return dst


def get(home, pin: dict, transport=None) -> dict:
    """Download and install the pinned build. Refused before any request while the github route is off."""
    home = _home(home)
    if _route_off():
        raise TerminalRefused("github.com is off: open it in Privacy to download the Lampway terminal (about 49 MB); nothing was sent")
    root = home / "addons" / "wezterm"
    root.mkdir(parents=True, exist_ok=True)
    vdir = root / pin["version"]
    part = root / (pin["asset"] + ".part")
    import httpx
    with E.context(kind="file", route=ROUTE), httpx.Client(transport=transport, follow_redirects=False, timeout=600.0) as client:
        try:
            digest = _fetch(client, pin["url"], part)
            if digest != pin["sha256"]:
                raise TerminalRefused("the download's SHA-256 does not match the pinned value: it was deleted; nothing was installed")
            sums = tempfile.NamedTemporaryFile(dir=root, delete=False)
            sums.close()
            _fetch(client, pin["url"] + ".sha256", Path(sums.name))
            published = Path(sums.name).read_text(encoding="utf-8").split()[0].strip().lower()
            os.unlink(sums.name)
            if published != pin["sha256"]:
                raise TerminalRefused("the release's published SHA-256 does not agree with the pinned value: nothing was installed")
            if pin.get("bytes") and part.stat().st_size != int(pin["bytes"]):
                raise TerminalRefused("the download's size is not the pinned size: nothing was installed")
            staging = Path(tempfile.mkdtemp(dir=root, prefix=".staging-"))
            binary = _unpack(pin, part, staging)
            lic = staging / "LICENSE.md"
            if pin.get("license_url"):
                _fetch(client, pin["license_url"], lic)
        except BaseException:
            part.unlink(missing_ok=True)
            raise
    size = part.stat().st_size
    part.unlink(missing_ok=True)
    if vdir.exists():
        shutil.rmtree(vdir)
    staging.rename(vdir)
    binary = vdir / binary.relative_to(staging)
    prov = {"version": pin["version"], "asset": pin["asset"], "url": pin["url"], "sha256": pin["sha256"], "bytes": size,
            "fetched_at": time.time(), "verified": True}
    (vdir / "PROVENANCE.json").write_text(json.dumps(prov, indent=1), encoding="utf-8")
    (root / "current").write_text(pin["version"], encoding="utf-8")
    write_config(home)
    return {"version": pin["version"], "binary": str(binary), "dir": str(vdir)}


def _unpack(pin: dict, part: Path, staging: Path) -> Path:
    kind = pin.get("kind")
    if kind == "appimage":
        out = staging / "wezterm.AppImage"
        shutil.copyfile(part, out)
        out.chmod(0o755)
        return out
    if kind == "tar":
        with tarfile.open(part) as tf:
            tf.extractall(staging, filter="data")
        return next(staging.rglob("wezterm"))
    if kind == "zip":
        with zipfile.ZipFile(part) as zf:
            zf.extractall(staging)
        return next((p for p in staging.rglob("wezterm*") if p.is_file()), staging)
    raise TerminalRefused(f"unknown archive kind {kind!r}")


def binary(home) -> Optional[Path]:
    home = _home(home)
    cur = home / "addons" / "wezterm" / "current"
    if not cur.exists():
        return None
    vdir = cur.parent / cur.read_text(encoding="utf-8").strip()
    found = [p for p in (vdir / "wezterm.AppImage",) if p.exists()] or [p for p in vdir.rglob("wezterm") if p.is_file()]
    return found[0] if found else None


def installed_version(home) -> Optional[str]:
    cur = _home(home) / "addons" / "wezterm" / "current"
    return cur.read_text(encoding="utf-8").strip() if cur.exists() else None


# ------------------------------------------------------------------------------------------------------ the tab bar's state
# DESIGN.md 13's cue for each cockpit Spark (server/lampway_server/workbench_view.py): waiting on the user reads as blocked
CUE_OF_SPARK = {"working": "working", "waiting": "blocked", "unread": "unread", "idle": "idle", "ended": "done"}


def state_doc(inst: dict, sessions: list, indicator: dict, routes: list) -> dict:
    """What the config's tab titles and status read (section 5): each Lampway pane that shows an agent, by its cue and name,
    and whether data leaves the machine."""
    from ..workbench_view import _spark
    by_id = {s["id"]: s for s in sessions or []}
    panes = {}
    for pane_id, rec in sorted((inst or {}).get("panes", {}).items()):
        s = by_id.get((rec or {}).get("herdr_agent_id"))
        if s is not None:
            panes[str(pane_id)] = {"state": CUE_OF_SPARK.get(_spark(s), "idle"), "name": s.get("name") or s["id"]}
    labels = {r["id"]: r.get("label") or r["id"] for r in routes or []}
    if (indicator or {}).get("over_the_wire"):
        egress = {"state": "live", "route": ", ".join(labels.get(a, a) for a in indicator.get("active") or []), "size": ""}
    else:
        n = sum(1 for r in routes or [] if r.get("enabled"))
        egress = {"state": "open", "open": f"{n} route{'' if n == 1 else 's'} open"} if n else {"state": "idle"}
    return {"panes": panes, "egress": egress}


def write_state(home, doc: dict) -> bool:
    """Write ``state.json`` whole (a reader never sees half a file); False, and nothing written, when it already says this."""
    p = _home(home) / "wezterm" / "state.json"
    text = json.dumps(doc, sort_keys=True)
    if p.exists() and p.read_text(encoding="utf-8") == text:
        return False
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(p)
    return True


# ------------------------------------------------------------------------------------------------------ the window
def socket_path(home) -> Path:
    return _home(home) / "wezterm" / "gui.sock"


def _instance_path(home) -> Path:
    return _home(home) / "wezterm" / "instance.json"


def load_instance(home) -> dict:
    p = _instance_path(home)
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {"gui_pid": None, "socket": str(socket_path(home)), "panes": {}}


def save_instance(home, inst: dict) -> None:
    p = _instance_path(home)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".tmp")
    tmp.write_text(json.dumps(inst, indent=1), encoding="utf-8")
    tmp.replace(p)


def _env(home, herdr_root=None) -> dict:
    home = _home(home)
    env = {k: v for k, v in os.environ.items() if not k.startswith(("HERDR_", "WEZTERM_"))}
    if herdr_root is not None:
        from ..herdr import launcher as L
        env.update({k: v for k, v in L.env_for(herdr_root).items() if k.startswith("HERDR_")})
    # Lampway's WezTerm never sees the person's WezTerm state (~/.local/share/wezterm, the runtime sockets of their own
    # WezTerm, ~/.config/wezterm): every directory WezTerm reads or writes is Lampway's own.
    base = home / "wezterm"
    dirs = {"HOME": base / "home", "XDG_RUNTIME_DIR": base / "run", "XDG_DATA_HOME": base / "data", "XDG_CONFIG_HOME": base / "config",
            "XDG_CACHE_HOME": base / "cache", "XDG_STATE_HOME": base / "state"}
    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True, mode=0o700)
    env.update({k: str(v) for k, v in dirs.items()})
    env.update(LAMPWAY_HOME=str(home), WEZTERM_UNIX_SOCKET=str(socket_path(home)), APPIMAGE_EXTRACT_AND_RUN="1")
    env.setdefault("LAMPWAY_THEME", "night")
    return env


def _config(home) -> str:
    return str(_home(home) / "wezterm" / "lampway.wezterm.lua")


def launch(home, exe: str, herdr_root=None, position: Optional[str] = None, detached: bool = True, bootstrap=None) -> dict:
    """Start Lampway's window (detached: it outlives Blender) and record its pid; it is the only process Remove may signal."""
    home = _home(home)
    socket_path(home).parent.mkdir(parents=True, exist_ok=True)
    cmd = [exe, "--config-file", _config(home), "start", "--always-new-process", "--class", CLASS, "--workspace", "lampway"]
    if position:
        cmd += ["--position", position]
    if bootstrap:
        cmd += ["--", *bootstrap]
    env = _env(home, herdr_root)
    if detached:
        proc = subprocess.Popen(cmd, env=env, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)
        pid = proc.pid
    else:
        subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=60)
        pid = None
    inst = load_instance(home)
    inst.update(gui_pid=pid, socket=str(socket_path(home)), started_at=time.time())
    save_instance(home, inst)
    return inst


def gui_socket(home) -> Optional[Path]:
    """The socket Lampway's window listens on: the one its bootstrap pane recorded, else the only GUI socket in Lampway's own
    runtime directory (the person's WezTerm sockets live in theirs, which no Lampway process is given)."""
    home = _home(home)
    rec = load_instance(home).get("socket")
    if rec and Path(rec).exists():
        return Path(rec)
    found = sorted((home / "wezterm" / "run" / "wezterm").glob("gui-sock-*"))
    return found[-1] if found else None


def cli(home, exe: str, args: list, timeout: int = 20) -> str:
    """One WezTerm CLI call aimed at Lampway's window only (its class, its socket), never starting a mux server."""
    cmd = [exe, "--config-file", _config(home), "cli", "--no-auto-start", "--class", CLASS, *map(str, args)]
    env = _env(home)
    sock = gui_socket(home)
    if sock is not None:
        env["WEZTERM_UNIX_SOCKET"] = str(sock)
    r = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=timeout)
    if r.returncode != 0:
        raise TerminalRefused((r.stderr or r.stdout).strip()[:300] or "the Lampway terminal did not answer")
    return r.stdout


def _ours(home, pane_id) -> bool:
    return str(pane_id) in (load_instance(home).get("panes") or {})


def send_text(home, exe: str, pane_id, text: str) -> None:
    if not _ours(home, pane_id):
        raise TerminalRefused(f"pane {pane_id} is not a Lampway pane: nothing was sent")
    cli(home, exe, ["send-text", "--pane-id", str(pane_id), "--no-paste", text])


def focus(home, exe: str, pane_id) -> None:
    if not _ours(home, pane_id):
        raise TerminalRefused(f"pane {pane_id} is not a Lampway pane: nothing was focused")
    cli(home, exe, ["activate-pane", "--pane-id", str(pane_id)])


ATTACHABLE = ("claude", "codex", "opencode")    # sessions herdr runs as a detected agent (`herdr agent start`)


def agent_tabs(home, exe: str, sessions: list) -> list:
    """One tab per live agent (section 6.3): `cli spawn --cwd <its folder> -- herdr agent attach <its pane>` for each live
    session the window has no tab for, recorded in the registry so it is spawned once (a tab the user closed stays closed).
    Only an agent herdr detects can be attached to (measured: a command pane is refused, agent_not_found): command and
    shell sessions stay in the window's first tab, herdr's own view of every session. Nothing while the window is not
    running. Returns the new WezTerm pane ids."""
    inst = load_instance(home)
    if not _alive(inst.get("gui_pid")):
        return []
    from ..herdr import launcher as L
    shown = {(rec or {}).get("herdr_agent_id") for rec in (inst.get("panes") or {}).values()}
    new = []
    for s in sessions or []:
        if s.get("state") != "live" or s.get("agent") not in ATTACHABLE or not s.get("pane_id") or s["id"] in shown:
            continue
        out = cli(home, exe, ["spawn", "--cwd", s.get("cwd") or str(_home(home)), "--", L.bin_path(), "agent", "attach", s["pane_id"]])
        pane = out.strip().splitlines()[-1].strip() if out.strip() else ""
        if not pane:
            continue
        inst = load_instance(home)
        inst.setdefault("panes", {})[pane] = {"herdr_agent_id": s["id"], "created_at": time.time()}
        save_instance(home, inst)
        new.append(pane)
    return new


def _alive(pid) -> bool:
    if not pid:
        return False
    try:
        os.kill(int(pid), 0)
    except (ProcessLookupError, PermissionError, ValueError):
        return False
    return True


def reconcile(home, exe: str) -> dict:
    """On Lampway's start: re-adopt the window when the recorded pid lives and its CLI answers; spawn nothing, touch no other pane."""
    inst = load_instance(home)
    ours = sorted((inst.get("panes") or {}).keys())
    if not _alive(inst.get("gui_pid")):
        return {"window": "gone", "panes": ours, "foreign_panes": []}
    try:
        listed = json.loads(cli(home, exe, ["list", "--format", "json"]) or "[]")
    except (TerminalRefused, ValueError, subprocess.TimeoutExpired):
        return {"window": "gone", "panes": ours, "foreign_panes": []}
    ids = sorted({str(p.get("pane_id")) for p in listed})
    return {"window": "re-adopted", "panes": [p for p in ours if p in ids], "foreign_panes": [p for p in ids if p not in ours]}


def _signal(pid) -> None:
    """End Lampway's window: it was started in its own session, so its process group is its own (the AppImage runtime and the
    GUI it runs); nothing outside that group is signalled."""
    try:
        if os.getpgid(int(pid)) == int(pid):
            os.killpg(int(pid), signal.SIGTERM)
            return
    except (ProcessLookupError, PermissionError):
        return
    os.kill(int(pid), signal.SIGTERM)


def remove(home, alive: Callable = _alive) -> dict:
    """Stop Lampway's own window (the pid it recorded at launch, never another WezTerm) and delete the add-on."""
    home = _home(home)
    inst = load_instance(home)
    stopped = None
    if inst.get("gui_pid") and alive(inst["gui_pid"]):
        _signal(inst["gui_pid"])
        stopped = inst["gui_pid"]
    shutil.rmtree(home / "addons" / "wezterm", ignore_errors=True)
    inst.update(gui_pid=None, panes={})
    save_instance(home, inst)
    return {"stopped": stopped, "removed": True}
