"""The card builder (specs/mrmak/09-report-cards.md sections 5 and 6.3): report pages generated from what Lampway already records (the experiment ledger, the prompt run
log). Standard library only; deterministic (the same data gives the same bytes: no clock in a page, every list in a fixed order); every value escaped. Media the page shows
is copied into the card's own folder, so the content server never has to serve anything outside the card tree.

- design_versions: one round of a piece: the BASE (the chosen take of the latest earlier round), the variants with model, cost and its source, rating and note, the saved
  prompt (template@version, the variables, the rendered text) in a ``<details>``, what each variant changes, the pick and its reason. Rejected takes stay, labelled.
- motion_tests: each clip with its start frame, template, the question it tests, gates, verdict and ledger id; clips of one question under one heading.
- receipt: the piece's four cost quantities (``Ledger.receipt``) with each credit price's source."""
from __future__ import annotations

import html
import json
import shutil
from pathlib import Path

from .assets import REPORT_CSS, REPORT_JS
from .registry import CardError

MARK = "<!-- generated by lampway_cards; edits are overwritten: change the data -->"
KINDS = ("design_versions", "motion_tests", "receipt")
IMAGES = (".png", ".jpg", ".jpeg", ".webp", ".gif")


def e(v) -> str:
    return html.escape("" if v is None else str(v), quote=True)


def _page(title: str, body: str) -> str:
    return (f"{MARK}\n<!doctype html>\n<html lang=\"en\" data-lw-report=\"document\"><head><meta charset=\"utf-8\"><title>{e(title)}</title>"
            f"<link rel=\"stylesheet\" href=\"../_shared/report.css\"></head>\n<body><main>\n<h1>{e(title)}</h1>\n{body}\n</main>"
            f"<script src=\"../_shared/report.js\"></script></body></html>\n")


def _shared(reg) -> None:
    d = reg.dir / "_shared"
    d.mkdir(parents=True, exist_ok=True)
    for name, text in (("report.css", REPORT_CSS), ("report.js", REPORT_JS)):
        p = d / name
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.write_text(text, encoding="utf-8")


def _media(reg, card_dir: Path, rel) -> str | None:
    """Copy a project file into the card's media folder; the page links the copy. None when the file is not there."""
    if not rel:
        return None
    src = Path(rel) if Path(rel).is_absolute() else reg.root / rel
    if not src.is_file():
        return None
    dst = card_dir / "media" / src.name
    dst.parent.mkdir(parents=True, exist_ok=True)
    if not dst.exists() or dst.stat().st_size != src.stat().st_size:
        shutil.copyfile(src, dst)
    return f"media/{src.name}"


def _img(reg, card_dir, rel, alt) -> str:
    link = _media(reg, card_dir, rel)
    return f'<img src="{e(link)}" alt="{e(alt)}">' if link else f'<p class="muted">{e(alt)}: the file is not in the project ({e(rel or "none recorded")})</p>'


def _cost(c: dict) -> str:
    parts = []
    if c.get("developer_api_usd") is not None:
        parts.append(f"${c['developer_api_usd']:.2f} API")
    if c.get("generation_credits") is not None:
        parts.append(f"{c['generation_credits']} credits ({c.get('price_source') or 'source not recorded'})")
    if c.get("subscription"):
        parts.append(f"subscription: {c['subscription']}")
    return ", ".join(parts) or "no cost recorded"


def _runs_by_ledger(runlog) -> dict:
    return {r.get("ledger_id"): r for r in runlog.runs() if r.get("ledger_id")}


def _round(rows, round_):
    rounds = sorted({str(r["settings"].get("round")) for r in rows if r["stage"] == "image" and r["settings"].get("round") is not None}, key=lambda x: (len(x), x))
    if not rounds:
        raise CardError("no design rounds recorded for this piece: nothing to report")
    if round_ in (None, "", "auto"):
        return rounds[-1]
    if str(round_) not in rounds:
        raise CardError(f"no round {round_!r}; the rounds are {rounds}")
    return str(round_)


def _design(reg, card_dir, rows, runs, piece, round_) -> tuple:
    rnd = _round(rows, round_)
    key = lambda r: (str(r["settings"].get("variant") or ""), r["id"])  # noqa: E731
    variants = sorted((r for r in rows if r["stage"] == "image" and str(r["settings"].get("round")) == rnd and r["settings"].get("variant")), key=key)
    earlier = [r for r in rows if r["stage"] == "image" and r.get("decision") == "chosen" and str(r["settings"].get("round")) < rnd]
    base = sorted(earlier, key=lambda r: (str(r["settings"].get("round")), r["id"]))[-1] if earlier else None
    pick = next((r for r in sorted(rows, key=lambda r: r["id"]) if r["stage"] == "decision" and str(r["settings"].get("round")) == rnd and r["settings"].get("pick")), None)
    review = next((r for r in rows if r["stage"] == "decision" and str(r["settings"].get("round")) == rnd and r["settings"].get("question") == "design_review"), None)
    out = []
    if base:
        brun = runs.get(base["id"]) or {}
        out.append(f'<h2>BASE (round {e(base["settings"].get("round"))})</h2><div class="grid"><div class="cell base">'
                   f'{_img(reg, card_dir, brun.get("output"), "BASE " + piece)}<p>{e(base.get("reason"))}</p><p class="tag">ledger {e(base["id"])}</p></div></div>')
    out.append(f"<h2>Round {e(rnd)}: the variants</h2><div class=\"grid\">")
    variables = {v["id"]: (runs.get(v["id"]) or {}).get("variables") or {} for v in variants}
    for v in variants:
        run, letter = runs.get(v["id"]) or {}, v["settings"]["variant"]
        chosen = pick and pick["settings"].get("pick") == letter
        mark = ("<span class=\"mark-chosen\">chosen</span>" if chosen else "<span class=\"mark-rejected\">not chosen</span>") if pick else ""
        others = [variables[o["id"]] for o in variants if o["id"] != v["id"]]
        changes = sorted(k for k, val in variables[v["id"]].items() if any(o.get(k) != val for o in others))
        out.append(f'<div class="cell {"chosen" if chosen else ("rejected" if pick else "")}"><h3>{e(letter)} {mark}</h3>'
                   f'{_img(reg, card_dir, run.get("output"), f"variant {letter} of {piece} round {rnd}")}'
                   f'<p class="tag">{e(v["settings"].get("model") or run.get("model"))} · {e(_cost(v["cost"]))}</p>'
                   f'<p>rating {e(run.get("rating") or "not rated")}{(": " + e(run.get("note"))) if run.get("note") else ""}</p>'
                   f'<p>What it changes: {e(", ".join(f"{k}={variables[v["id"]][k]}" for k in changes) or "nothing in its variables")}</p>'
                   f'<details><summary>Saved generation prompt</summary><p class="tag">{e(run.get("template") or "no template")} · '
                   f'{e(json.dumps(run.get("variables") or {}, sort_keys=True))}</p><pre>{e(run.get("prompt") or "not recorded")}</pre></details>'
                   f'<p class="tag">ledger {e(v["id"])}</p></div>')
    out.append("</div>")
    if review:
        out.append(f"<h2>Design review</h2><p>{e(review.get('reason'))}</p>")
    if pick:
        out.append(f"<h2>Decision</h2><p>{e(pick['settings'].get('pick'))} by {e(pick.get('by'))}: {e(pick.get('reason'))}</p>")
    return f"Round {rnd}", f"round-{rnd}.html", "".join(out)


def _motion(reg, card_dir, rows, runs, piece) -> tuple:
    clips = sorted((r for r in rows if r["stage"] in ("video", "motion")), key=lambda r: (str(r["settings"].get("question") or ""), r["id"]))
    if not clips:
        raise CardError(f"no motion tests recorded for {piece}: nothing to report")
    out, question = [], None
    for c in clips:
        s, run = c["settings"], runs.get(c["id"]) or {}
        if s.get("question") != question:
            question = s.get("question")
            out.append(f"<h2>{e(question or 'Clips')}</h2>")
        link = _media(reg, card_dir, s.get("clip") or run.get("output"))
        player = f'<video controls src="{e(link)}"></video><p><a href="{e(link)}" download>Download</a></p>' if link else \
            f'<p class="muted">the clip is not in the project ({e(s.get("clip") or "none recorded")})</p>'
        gates = run.get("gates") or {}
        out.append(f'<div class="cell">{player}{_img(reg, card_dir, s.get("start_frame"), "start frame of " + c["id"])}'
                   f'<p class="tag">{e(s.get("template") or run.get("template") or "no template")} · {e(_cost(c["cost"]))}</p>'
                   f'<div class="scroll"><table><tr><th>gate</th><th>value</th></tr>'
                   + "".join(f"<tr><td>{e(k)}</td><td>{e(v)}</td></tr>" for k, v in sorted(gates.items())) +
                   f'</table></div><p>verdict: {e(c.get("decision") or "none")} · {e(json.dumps(c.get("verdict") or {}, sort_keys=True))}</p><p class="tag">ledger {e(c["id"])}</p></div>')
    return "Motion tests", "motion-tests.html", "".join(out)


def _receipt(ledger, rows, piece) -> tuple:
    r = ledger.receipt(piece)
    sources = sorted({str(x["cost"].get("price_source")) for x in rows if x["cost"].get("price_source")})
    body = (f'<div class="scroll"><table><tr><th>quantity</th><th>total</th></tr><tr><td>generation credits</td><td>{e(r["generation_credits"])}</td></tr>'
            f'<tr><td>developer API</td><td>${r["developer_api_usd"]:.2f}</td></tr><tr><td>work</td><td>{e(r["work_s"])} s</td></tr>'
            f'<tr><td>subscriptions</td><td>{e(", ".join(r["subscription"]) or "none")}</td></tr></table></div>'
            f'<p>{e(r["rows"])} rows. Credit prices read back from: {e(", ".join(sources) or "none recorded")}.</p>')
    return "Receipt", "receipt.html", body


def build(reg, ledger, runlog, card_id: str, kind: str, piece: str, round_="auto", title=None) -> str:
    if kind not in KINDS:
        raise CardError(f"kind is one of {list(KINDS)}")
    card = reg.get(card_id)
    rows = ledger.list(piece=piece)
    if not rows:
        raise CardError(f"no runs recorded for {piece}: nothing to report")
    runs = _runs_by_ledger(runlog)
    card_dir = reg.card_dir(card)
    card_dir.mkdir(parents=True, exist_ok=True)
    _shared(reg)
    if kind == "design_versions":
        name, fname, body = _design(reg, card_dir, rows, runs, piece, round_)
    elif kind == "motion_tests":
        name, fname, body = _motion(reg, card_dir, rows, runs, piece)
    else:
        name, fname, body = _receipt(ledger, rows, piece)
    text = _page(title or f"{piece}: {name}", body)
    out = card_dir / fname
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
    reg.set_step(card_id, name, fname)
    return str(out)
