# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
# SPDX-FileCopyrightText: 2026 Lampway contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Render the desktop app's brand from the ONE template: its loopback sign-in pages (server/lampway_server/brand_page.py) into
src/scripts/mixar/modules/auth/core/sso_pages.py (the Python callback) and src/source/creator/mixar_sso_success_page.h
(the native callback), and the phone camera page's brand.css and lockup (virtual_camera/webapp). The site's faces are subset to the characters each page shows (fontTools, at generation only),
so a native page stays a C literal under the 64 KB MSVC allows for a concatenated string.

    python3 scripts/generate_sso_success_page.py          # write both files (needs fontTools and brotli)
    python3 scripts/generate_sso_success_page.py --check  # exit 1 when a file's markup differs from the template's
                                                          # (the font payloads are not compared: no fontTools needed)
"""

import html
import importlib.util
import io
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PY_OUT = ROOT / "src/scripts/mixar/modules/auth/core/sso_pages.py"
C_OUT = ROOT / "src/source/creator/mixar_sso_success_page.h"
CAMERA = ROOT / "src/scripts/mixar/modules/virtual_camera/webapp"   # the phone camera page: brand.css and the lockup
MSVC_LIMIT = 65535
_spec = importlib.util.spec_from_file_location("brand_page", ROOT / "server/lampway_server/brand_page.py")
BP = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(BP)

WHERE = "the sign-in window"
PAGES = {   # name -> keyword arguments of brand_page.callback (the desktop app signs in to Lampway itself)
    "SUCCESS_PAGE": dict(service="Lampway", outcome="ok"),
    "EXPIRED_PAGE": dict(service="Lampway", outcome="expired", where=WHERE),
    "FAILURE_PAGE": dict(service="Lampway", outcome="error", where=WHERE,
                         reason="The sign-in did not return a code Lampway could use."),
}
PY_PAGES = ("SUCCESS_PAGE", "EXPIRED_PAGE")          # sso.py answers a good callback and a state mismatch
C_PAGES = ("SUCCESS_PAGE", "FAILURE_PAGE")           # mixar_local_auth_server.cc answers a code or none
FONT = re.compile(r"base64,[A-Za-z0-9+/=]+")


def _render(name, faces=None) -> str:
    kw = dict(PAGES[name])
    return BP.callback(kw.pop("service"), kw.pop("outcome"), faces=faces, **kw)


def _subset_faces(text: str) -> dict:
    from fontTools import subset
    from fontTools.ttLib import TTFont
    out = {}
    for name, data in BP.face_bytes().items():
        font = TTFont(io.BytesIO(data))
        opts = subset.Options()
        opts.flavor = "woff2"
        opts.layout_features = ["kern", "liga"]
        sub = subset.Subsetter(opts)
        sub.populate(text=text)
        sub.subset(font)
        buf = io.BytesIO()
        font.flavor = "woff2"
        font.save(buf)
        out[name] = buf.getvalue()
    return out


def _visible(page: str) -> str:
    body = page[page.index("<body>"):]
    return html.unescape(re.sub(r"<[^>]+>", " ", body)) + " .,:;()'-0123456789"


def render_all() -> dict:
    pages = {}
    for name in PAGES:
        plain = _render(name)
        pages[name] = _render(name, _subset_faces(_visible(plain)))
    return pages


def py_file(pages) -> str:
    out = ['# SPDX-FileCopyrightText: 2026 Lampway contributors', '#', '# SPDX-License-Identifier: GPL-3.0-or-later', '',
           '"""GENERATED by scripts/generate_sso_success_page.py from server/lampway_server/brand_page.py; do not edit.',
           '',
           'The desktop app\'s loopback sign-in pages: self-contained (faces and mark inlined, no script), so nothing is requested',
           'after the callback server shuts down. The faces are Fraunces and IBM Plex Sans (SIL OFL 1.1, texts in',
           'server/lampway_server/web/brand/fonts/), subset to the characters each page shows."""', '']
    for name in PY_PAGES:
        chunks = [pages[name][i:i + 2000] for i in range(0, len(pages[name]), 2000)]
        out.append(f"{name} = \"\".join([")
        out += [f"    {json.dumps(c, ensure_ascii=False)}," for c in chunks]
        out.append("]).encode(\"utf-8\")")
        out.append("")
    return "\n".join(out)


def c_file(pages) -> str:
    out = ["// SPDX-FileCopyrightText: 2026 Lampway contributors", "// SPDX-License-Identifier: GPL-3.0-or-later",
           "// GENERATED by scripts/generate_sso_success_page.py from server/lampway_server/brand_page.py; do not edit.",
           "// The native loopback's pages; faces Fraunces and IBM Plex Sans (SIL OFL 1.1), subset to each page's characters.",
           "#pragma once", ""]
    for name in C_PAGES:
        size = len(pages[name].encode("utf-8"))
        if size >= MSVC_LIMIT:
            raise SystemExit(f"{name} is {size} bytes: over the {MSVC_LIMIT}-byte literal MSVC allows")
        out.append(f"static const char *{name} =")
        out += [f"    {json.dumps(pages[name][i:i + 1000], ensure_ascii=False)}" for i in range(0, len(pages[name]), 1000)]
        out[-1] += ";"
        out.append("")
    return "\n".join(out)


def _norm(page: str) -> str:
    return FONT.sub("base64,FONT", page)


def _read_py() -> dict:
    ns = {}
    exec(compile(PY_OUT.read_text(encoding="utf-8"), str(PY_OUT), "exec"), ns)   # the generated file: constants only
    return {name: ns[name].decode("utf-8") for name in PY_PAGES if name in ns}


def _read_c() -> dict:
    text = C_OUT.read_text(encoding="utf-8")
    pages = {}
    for name in C_PAGES:
        m = re.search(rf"static const char \*{name} =\n((?:    \".*\"\n?)+);", text + "\n")
        if not m:
            m = re.search(rf"static const char \*{name} =\n((?:    \".*\"[;]?\n)+)", text)
        if m:
            pages[name] = "".join(json.loads(line.strip().rstrip(";")) for line in m.group(1).splitlines() if line.strip())
    return pages


def camera_files() -> dict:
    """The phone camera page's brand (served from the app, never from a CDN): faces, the Night tokens (its controls sit over the
    live picture, so it stays Night) and the lockup, from the template."""
    head = "/* SPDX-FileCopyrightText: 2026 Lampway contributors */\n/* SPDX-License-Identifier: GPL-3.0-or-later */\n" \
           "/* GENERATED by scripts/generate_sso_success_page.py from server/lampway_server/brand_page.py; do not edit. */\n"
    return {CAMERA / "brand.css": head + BP.faces_css() + BP.tokens_css(night_only=True) + "\n", CAMERA / "lockup.svg": BP.mark_svg()}


def check() -> list:
    want = {name: _norm(_render(name)) for name in PAGES}
    problems = [f"{path.name} is stale (run scripts/generate_sso_success_page.py)"
                for path, text in camera_files().items() if not path.exists() or path.read_text(encoding="utf-8") != text]
    for where, got in (("sso_pages.py", _read_py()), ("mixar_sso_success_page.h", _read_c())):
        names = PY_PAGES if where.endswith(".py") else C_PAGES
        for name in names:
            if name not in got:
                problems.append(f"{where}: {name} is missing")
            elif _norm(got[name]) != want[name]:
                problems.append(f"{where}: {name} differs from the template (run scripts/generate_sso_success_page.py)")
            elif where.endswith(".h") and len(got[name].encode("utf-8")) >= MSVC_LIMIT:
                problems.append(f"{where}: {name} is over the MSVC literal limit")
    return problems


if __name__ == "__main__":
    if "--check" in sys.argv:
        problems = check()
        for p in problems:
            print(p)
        print("sso pages: " + ("stale" if problems else "current"))
        sys.exit(1 if problems else 0)
    for path, text in camera_files().items():
        path.write_text(text, encoding="utf-8")
    if not [p for p in check() if p.startswith(("sso_pages.py", "mixar_sso_success_page.h"))]:
        # the subset fonts are not byte-stable between fontTools runs: pages whose markup is current are left as they are,
        # so the native header (and with it a rebuild) changes only when the template does
        print("sso pages: current (left as they are)")
        sys.exit(0)
    pages = render_all()
    PY_OUT.write_text(py_file(pages), encoding="utf-8")
    C_OUT.write_text(c_file(pages), encoding="utf-8")
    print(f"wrote {PY_OUT.relative_to(ROOT)} and {C_OUT.relative_to(ROOT)}: " +
          ", ".join(f"{n} {len(p.encode('utf-8'))} bytes" for n, p in pages.items()))
