#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Lampway contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Glance-cue gate (DESIGN.md 13): the cue table in tokens.json must read without colour and stay calm.

    python3 check_cues.py               # exit 1 on a finding; writes cues_report.md (colour distances)
    python3 check_cues.py --self-test   # plants one offender per check

C1  within a family every state has its own glyph (shape alone tells them apart: greyscale, deuteranopia, protanopia).
C2  only the live-egress cue moves.
C3  only a cue that waits for the user glows (blocked, waiting for your click, waiting for your confirm).
C4  every state that asks for attention differs from its family's resting state by colour in at least one of normal vision,
    deuteranopia, protanopia (CIE76 delta E >= 12) AND by greyscale lightness (delta L* >= 8) or by glyph; reported per pair.
Simulation: Machado, Oliveira and Fernandes (2009) matrices at severity 1.0, applied in linear sRGB.
"""
import copy
import itertools
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
T = json.load(open(os.path.join(HERE, "tokens.json")))
MACHADO = {
    "deutan": [[0.367322, 0.860646, -0.227968], [0.280085, 0.672501, 0.047413], [-0.011820, 0.042940, 0.968881]],
    "protan": [[0.152286, 1.052583, -0.204868], [0.114503, 0.786281, 0.099216], [-0.003882, -0.048116, 1.051998]],
}
REST = {"agent": "idle", "spend": "under a cap", "egress": "idle, nothing can leave", "route": "off", "build": "Planned",
        "connection": "connected",   # specs/connections/connections_face.md 5.3
        "choice": "served by the preferred option"}   # specs/choices/choices_face.md 5.3
WAITS = ("blocked", "waiting", "waits for you")


def lin(c):
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def lab(rgb_lin):
    r, g, b = rgb_lin
    x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047
    y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883
    f = lambda t: t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116  # noqa: E731
    return (116 * f(y) - 16, 500 * (f(x) - f(y)), 200 * (f(y) - f(z)))


def colour(tok, variant="dark"):
    hx = T["colour"][tok][variant].lstrip("#")
    return [lin(int(hx[i:i + 2], 16) / 255) for i in (0, 2, 4)]


def sim(rgb, kind):
    if kind == "normal":
        return rgb
    m = MACHADO[kind]
    return [max(0.0, min(1.0, sum(m[i][j] * rgb[j] for j in range(3)))) for i in range(3)]


def de(a, b):
    return sum((p - q) ** 2 for p, q in zip(a, b)) ** 0.5


def check(cues, report=None):
    f = []
    rows = []
    for fam, states in cues.items():
        if fam.startswith("_"):
            continue
        glyphs = [s["glyph"] for s in states]
        if len(set(glyphs)) != len(glyphs):
            f.append(f"C1 {fam}: two states share a glyph ({glyphs})")
        for s in states:
            if s["motion"] != "none" and not (fam == "egress" and s["state"].startswith("live")):
                f.append(f"C2 {fam}/{s['state']} moves (only live egress may)")
            if s["glow"] and not any(w in s["state"] for w in WAITS):
                f.append(f"C3 {fam}/{s['state']} glows but does not wait for the user")
        rest = next(s for s in states if s["state"] == REST[fam])
        for s in states:
            if s is rest:
                continue
            for variant in ("dark", "light"):
                a, b = colour(rest["colour"], variant), colour(s["colour"], variant)
                d = {k: de(lab(sim(a, k)), lab(sim(b, k))) for k in ("normal", "deutan", "protan")}
                dl = abs(lab(a)[0] - lab(b)[0])
                glyph_differs = rest["glyph"] != s["glyph"]
                ok = max(d.values()) >= 12 and (dl >= 8 or glyph_differs)
                rows.append(f"| {fam} | {rest['state']} vs {s['state']} | {variant} | {d['normal']:.0f} | {d['deutan']:.0f} | {d['protan']:.0f} | {dl:.0f} | {'yes' if glyph_differs else 'no'} | {'ok' if ok else 'FAIL'} |")
                if not ok:
                    f.append(f"C4 {fam}: {s['state']} vs {rest['state']} ({variant}) is not distinguishable enough")
    if report:
        open(report, "w").write(
            "<!-- SPDX-FileCopyrightText: 2026 Lampway contributors -->\n<!-- SPDX-License-Identifier: GPL-3.0-or-later -->\n\n"
            "# Glance cues: colour distances (generated by check_cues.py)\n\nEach attention state against its family's resting state. "
            "Delta E is CIE76 in L*a*b*; deutan and protan use Machado et al. 2009 at severity 1.0; delta L* is the greyscale difference. "
            "Shape is the primary channel (every state has its own glyph); colour confirms.\n\n"
            "| family | pair | theme | dE normal | dE deutan | dE protan | dL* grey | glyph differs | result |\n|---|---|---|---|---|---|---|---|---|\n"
            + "\n".join(rows) + "\n")
    return f


def self_test():
    assert not check(T["cues"]), "the cue table must be clean before the self-test"
    ok = True
    plants = []
    c = copy.deepcopy(T["cues"]); c["agent"][1]["glyph"] = c["agent"][0]["glyph"]; plants.append(("C1 shared glyph", c, "C1"))
    c = copy.deepcopy(T["cues"]); c["agent"][1]["motion"] = "flame-flicker"; plants.append(("C2 working flame moves", c, "C2"))
    c = copy.deepcopy(T["cues"]); c["agent"][5]["glow"] = True; plants.append(("C3 done glows", c, "C3"))
    c = copy.deepcopy(T["cues"]); c["agent"][6]["colour"] = "line_hi"; c["agent"][6]["glyph"] = "ring"; plants.append(("C4 failed looks idle", c, "C4"))
    for label, cues, tag in plants:
        hit = any(x.startswith(tag) for x in check(cues))
        print(("caught  " if hit else "MISSED  ") + label)
        ok &= hit
    return ok


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        sys.exit(0 if self_test() else 1)
    fs = check(T["cues"], report=os.path.join(HERE, "cues_report.md"))
    for x in fs:
        print(x)
    print(f"check_cues: {len(fs)} finding(s)")
    sys.exit(1 if fs else 0)
