-- SPDX-FileCopyrightText: 2026 Lampway contributors
-- SPDX-License-Identifier: GPL-3.0-or-later
-- Lampway's own WezTerm configuration (contract 16). GENERATED by theme/build_theme.py from theme/tokens.json; do not edit.
-- Loaded ONLY through `wezterm --config-file <this file>`: it never reads, writes or includes the user's ~/.wezterm.lua.
-- Everything it reads lives under $LAMPWAY_HOME (the launcher always sets it).
local wezterm = require 'wezterm'
local config = wezterm.config_builder and wezterm.config_builder() or {}
local home = os.getenv('LAMPWAY_HOME') or error('LAMPWAY_HOME is not set: start the terminal from Lampway')
local variant = (os.getenv('LAMPWAY_THEME') == 'paper') and 'light' or 'dark'

config.color_schemes = {
  ['Lampway Night'] = {
    foreground = '#ECE8DF', background = '#0E1016',
    cursor_bg = '#EDB944', cursor_fg = '#0E1016', cursor_border = '#EDB944',
    selection_bg = '#5A4720', selection_fg = '#F7F4EE',
    scrollbar_thumb = '#3B4252', split = '#2B303D', compose_cursor = '#9EA0F7',
    ansi = { '#0E1016', '#F0766B', '#5BC48F', '#EDB944', '#9EA0F7', '#D58FE0', '#6FC3E8', '#CFCBC2' },
    brights = { '#7D7A73', '#F59A91', '#7FD6A8', '#F6CD6B', '#B9BBFA', '#E2AEEA', '#97D5F0', '#F7F4EE' },
  },
  ['Lampway Paper'] = {
    foreground = '#1B1B22', background = '#E4DCCB',
    cursor_bg = '#EDB944', cursor_fg = '#1B1B22', cursor_border = '#EDB944',
    selection_bg = '#EED9A0', selection_fg = '#0E1016',
    scrollbar_thumb = '#C9BFA9', split = '#DDD5C3', compose_cursor = '#4547B8',
    ansi = { '#1B1B22', '#B3372C', '#1F7A4D', '#8A5A00', '#4547B8', '#8A3A96', '#1F6E8C', '#C9BFA9' },
    brights = { '#5C5A55', '#C9483C', '#2A8F5C', '#A06A00', '#5A5CC8', '#A04AAE', '#2A86A8', '#F7F3EA' },
  },
}
config.color_scheme = (variant == 'light') and 'Lampway Paper' or 'Lampway Night'

-- type (decision F1: Inter for the UI, Plex Mono for every number and every terminal)
config.font_dirs = { home .. '/addons/wezterm/fonts' }
config.font = wezterm.font_with_fallback({ 'IBM Plex Mono', 'DejaVu Sans Mono' })
config.font_size = 11.5
config.line_height = 1.15

-- calm by default: no bell, no blinking, no update check (that would be an unannounced network call)
config.check_for_updates = false
config.automatically_reload_config = false
config.audible_bell = 'Disabled'
config.visual_bell = { fade_in_duration_ms = 0, fade_out_duration_ms = 0 }
config.cursor_blink_rate = 0
config.default_cursor_style = 'SteadyBar'
config.enable_kitty_graphics = true
config.window_padding = { left = 14, right = 14, top = 10, bottom = 8 }
-- a viewport, nothing more (the captain, 2026-10-06): herdr owns the workspace, the agents, the panes and the tabs, and shows
-- their state; WezTerm has no tab bar and mirrors nothing
config.enable_tab_bar = false
config.unix_domains = {}
config.ssh_domains = {}

-- images (contract 16, section 6.7): inline images do not cross herdr (measured live 2026-10-06, the iTerm2 and kitty
-- protocols both), so an image path in a pane's output is a link; a click appends it to a queue under $LAMPWAY_HOME that
-- Blender drains into its Image Editor. Only Lampway's own links are taken here; every other link opens as before.
local SHOW_QUEUE = home .. '/wezterm/show_in_blender.jsonl'
config.hyperlink_rules = wezterm.default_hyperlink_rules()
table.insert(config.hyperlink_rules, { regex = [[(?i)(/[^\s'"`<>|]+\.(?:png|jpe?g|exr|webp|tga|tiff?|bmp))\b]], format = 'lampway-image:$1' })
-- herdr takes the mouse (its panes report clicks), so a plain click goes to herdr; Ctrl+click opens a link in either mode
config.mouse_bindings = {}
for _, reporting in ipairs({ false, true }) do
  table.insert(config.mouse_bindings, { event = { Up = { streak = 1, button = 'Left' } }, mods = 'CTRL', mouse_reporting = reporting,
                                        action = wezterm.action.OpenLinkAtMouseCursor })
  table.insert(config.mouse_bindings, { event = { Down = { streak = 1, button = 'Left' } }, mods = 'CTRL', mouse_reporting = reporting,
                                        action = wezterm.action.Nop })
end
wezterm.on('open-uri', function(window, pane, uri)
  local path = uri:match('^lampway%-image:(.+)$')
  if not path then return end
  local f = io.open(SHOW_QUEUE, 'a')
  if f then
    f:write(wezterm.json_encode({ path = path, at = os.time() }) .. '\n')
    f:close()
  end
  return false
end)

return config
