#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Lampway contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate Lampway's PLACEHOLDER brand art.

Lampway is a fork of the GPL Mixar client; Mixar's logos, icons, mascot and
splash are licensed separately and must not ship in a fork. This tool
replaces every one of them with a neutral lamp glyph, drawn once (the
``GLYPH`` table below) and emitted in every format the build consumes:

* SVG (icon sources, freedesktop icons, the credit badges, the icon sheet)
* Blender ``.dat`` icons (16 and 32 px, headers kept as the build expects)
* PNG (splash, logo), lossless WebP (mascot), ICO (Windows), ICNS (macOS)

Rasters are drawn with Pillow from the same coordinates as the SVG, so no
SVG renderer is needed; output is deterministic for a given Pillow.

    python3 scripts/dev/lampway_placeholder_art.py            # write into the repo
    python3 scripts/dev/lampway_placeholder_art.py --out DIR  # write under DIR

Replace the outputs with real artwork when there is some; keep REUSE.toml's
annotation for these paths in step.
"""

from __future__ import annotations

import argparse
import pathlib
import importlib.util
import struct
import sys
import textwrap

from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).resolve().parents[2]
FONT = ROOT / "src/release/datafiles/fonts/Manrope-ExtraBold.ttf"

def _brand():
    """brand.py by file path: it must stay importable outside Blender (the same trick scripts/generate_config.py uses)."""
    path = pathlib.Path(__file__).resolve().parents[2] / "src/scripts/mixar/config/brand.py"
    spec = importlib.util.spec_from_file_location("lampway_brand", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_BRAND = _brand()
PRODUCT_NAME = _BRAND.PRODUCT_NAME
ATTRIBUTION_SHORT = _BRAND.ATTRIBUTION_SHORT
MARK = "Lampway placeholder art - generated by scripts/dev/lampway_placeholder_art.py"
SPDX = ("SPDX-FileCopyrightText: 2026 Lampway contributors",
        "SPDX-License-Identifier: GPL-3.0-or-later")

# Colours (RGB). The glow is the only accent; everything else is ink.
GLOW = (232, 184, 74)
INK = (38, 34, 30)
PAPER = (20, 20, 20)
TEXT = (226, 226, 226)

# The lamp, in a 100 x 100 unit square. Each row: (kind, params, fill, alpha).
#   ellipse: (cx, cy, rx, ry)   polygon: ((x, y), ...)   rect: (x0, y0, x1, y1)
GLYPH = (
    ("ellipse", (50, 40, 30, 30), GLOW, 90),            # soft glow
    ("polygon", ((30, 16), (70, 16), (84, 52), (16, 52)), INK, 255),  # shade
    ("ellipse", (50, 52, 9, 9), GLOW, 255),             # bulb
    ("rect", (46, 52, 54, 80), INK, 255),               # stem
    ("ellipse", (50, 84, 24, 7), INK, 255),             # base
)

# Small markers that make the four credit badges tell apart (same square).
BADGES = {
    "credits_upgrade": (("polygon", ((82, 92), (70, 78), (94, 78)), GLOW, 255),
                        ("rect", (79, 78, 85, 96), GLOW, 255)),
    "credits_slide": (("rect", (62, 86, 96, 90), GLOW, 255),
                      ("ellipse", (84, 88, 5, 5), GLOW, 255)),
    "credits_refer": (("ellipse", (74, 86, 6, 6), GLOW, 255),
                      ("ellipse", (90, 86, 6, 6), GLOW, 255)),
    "credits_creator": (("polygon", ((82, 74), (86, 84), (96, 84), (88, 90), (91, 100),
                                     (82, 94), (73, 100), (76, 90), (68, 84), (78, 84)), GLOW, 255),),
}


# ---------------------------------------------------------------------------
# SVG
# ---------------------------------------------------------------------------

def _hex(rgb):
    return "#%02x%02x%02x" % rgb


def _svg_shape(kind, params, fill, alpha, scale, dx=0.0, dy=0.0):
    opacity = "" if alpha == 255 else f' fill-opacity="{alpha / 255:.3f}"'
    if kind == "ellipse":
        cx, cy, rx, ry = params
        return (f'<ellipse cx="{dx + cx * scale:g}" cy="{dy + cy * scale:g}" '
                f'rx="{rx * scale:g}" ry="{ry * scale:g}" fill="{_hex(fill)}"{opacity}/>')
    if kind == "rect":
        x0, y0, x1, y1 = params
        return (f'<rect x="{dx + x0 * scale:g}" y="{dy + y0 * scale:g}" '
                f'width="{(x1 - x0) * scale:g}" height="{(y1 - y0) * scale:g}" '
                f'fill="{_hex(fill)}"{opacity}/>')
    points = " ".join(f"{dx + x * scale:g},{dy + y * scale:g}" for x, y in params)
    return f'<polygon points="{points}" fill="{_hex(fill)}"{opacity}/>'


def svg_document(width, height, shapes, extra_comment=""):
    lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    lines += [f"<!-- {line} -->" for line in SPDX]
    lines.append(f"<!-- {MARK} -->")
    if extra_comment:
        lines.append(f"<!-- {extra_comment} -->")
    lines.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
                 f'viewBox="0 0 {width} {height}">')
    lines += ["  " + s for s in shapes]
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def glyph_svg(size, badge=None, mono=None):
    scale = size / 100.0
    rows = list(GLYPH) + list(BADGES.get(badge, ()))
    if mono is not None:
        rows = [(k, p, mono, 255) for k, p, _f, a in rows if a == 255]
    return svg_document(size, size, [_svg_shape(k, p, f, a, scale) for k, p, f, a in rows])


def sheet_svg():
    """A 602 x 640 icon sheet holding only our 16 px cell at (257, 320):
    the position the shipped ``icon16_mixar_icon.dat`` header records, so
    Blender's icon-update script would cut the same cell."""
    shapes = [_svg_shape(k, p, f, a, 0.16, 257, 320) for k, p, f, a in GLYPH]
    return svg_document(602, 640, shapes,
                        "Only the Lampway cell is authored here; Blender's own icons live upstream.")


# ---------------------------------------------------------------------------
# Rasters
# ---------------------------------------------------------------------------

SUPERSAMPLE = 4


def render_glyph(size, badge=None, mono=None, margin=0.0):
    """RGBA square of ``size`` px, glyph fitted inside ``margin`` (fraction)."""
    big = size * SUPERSAMPLE
    image = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image, "RGBA")
    inner = big * (1.0 - 2 * margin)
    offset = big * margin
    scale = inner / 100.0
    rows = list(GLYPH) + list(BADGES.get(badge, ()))
    if mono is not None:
        rows = [(k, p, mono, 255) for k, p, _f, a in rows if a == 255]
    for kind, params, fill, alpha in rows:
        colour = (*fill, alpha)
        if kind == "ellipse":
            cx, cy, rx, ry = params
            box = (offset + (cx - rx) * scale, offset + (cy - ry) * scale,
                   offset + (cx + rx) * scale, offset + (cy + ry) * scale)
            draw.ellipse(box, fill=colour)
        elif kind == "rect":
            x0, y0, x1, y1 = params
            draw.rectangle((offset + x0 * scale, offset + y0 * scale,
                            offset + x1 * scale, offset + y1 * scale), fill=colour)
        else:
            draw.polygon([(offset + x * scale, offset + y * scale) for x, y in params], fill=colour)
    return image.resize((size, size), Image.LANCZOS)


def version() -> str:
    """The product version from the repo's VERSION file (one line)."""
    try:
        return (ROOT / "VERSION").read_text(encoding="utf-8").strip() or "dev"
    except OSError:
        return "dev"


def render_splash(width=1672, height=941):
    image = Image.new("RGBA", (width, height), (*PAPER, 255))
    glyph = render_glyph(int(height * 0.62), margin=0.04)
    image.alpha_composite(glyph, (int(width * 0.08), int(height * 0.14)))
    draw = ImageDraw.Draw(image)
    title = ImageFont.truetype(str(FONT), int(height * 0.18))
    small = ImageFont.truetype(str(FONT), int(height * 0.035))
    x = int(width * 0.46)
    draw.text((x, int(height * 0.30)), PRODUCT_NAME, font=title, fill=TEXT)
    draw.text((x, int(height * 0.56)), f"Open-source 3D workspace  ·  {version()}", font=small, fill=(*GLOW, 255))
    for i, row in enumerate(textwrap.wrap(ATTRIBUTION_SHORT, 62)):
        draw.text((x, int(height * (0.62 + 0.045 * i))), row, font=small, fill=(150, 150, 150, 255))
    return image


def render_mascot(width=632, height=725):
    image = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    glyph = render_glyph(width, margin=0.02)
    image.alpha_composite(glyph, (0, (height - width) // 2))
    return image


def icon_dat(size, origin, canvas):
    """Blender's icon ``.dat``: 6 little-endian ints (w, h, x, y, canvas w,
    canvas h) then raw RGBA. The origin/canvas values are what the shipped
    files carried; the build only reads w, h and the pixels."""
    pixels = render_glyph(size).tobytes()
    return struct.pack("<6i", size, size, origin[0], origin[1], canvas[0], canvas[1]) + pixels


# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------

def write(path: pathlib.Path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(data, str):
        path.write_text(data, encoding="utf-8")
    else:
        path.write_bytes(data)
    print(f"wrote {path}")


def generate(out: pathlib.Path):
    datafiles = out / "src/release/datafiles"
    icons_svg = datafiles / "icons_svg"
    write(icons_svg / "mixar_icon.svg", glyph_svg(1600))
    for badge in BADGES:
        write(icons_svg / f"{badge}.svg", glyph_svg(1600, badge=badge))
    write(datafiles / "mixar_icons.svg", sheet_svg())
    write(datafiles / "blender_icons16/icon16_mixar_icon.dat", icon_dat(16, (257, 320), (602, 640)))
    write(datafiles / "blender_icons32/icon32_mixar_icon.dat", icon_dat(32, (514, 640), (1204, 1280)))

    freedesktop = out / "src/release/freedesktop/icons"
    write(freedesktop / "scalable/apps/mixar.svg", glyph_svg(128))
    write(freedesktop / "symbolic/apps/mixar-symbolic.svg", glyph_svg(16, mono=(0, 0, 0)))

    buffer_png = datafiles / "mixar_logo.png"
    buffer_png.parent.mkdir(parents=True, exist_ok=True)
    render_glyph(256, margin=0.05).save(buffer_png, format="PNG")
    print(f"wrote {buffer_png}")
    splash = datafiles / "splash.png"
    render_splash().save(splash, format="PNG")
    print(f"wrote {splash}")

    mascot = out / "src/scripts/mixar/modules/common/notifications/assets/mixie_mascot.webp"
    mascot.parent.mkdir(parents=True, exist_ok=True)
    render_mascot().save(mascot, format="WEBP", lossless=True)
    print(f"wrote {mascot}")

    sizes = [(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
    windows = out / "src/release/windows/icons"
    windows.mkdir(parents=True, exist_ok=True)
    render_glyph(256, margin=0.04).save(windows / "winmixar.ico", format="ICO", sizes=sizes)
    render_glyph(256, badge="credits_slide", margin=0.04).save(
        windows / "winmixarfile.ico", format="ICO", sizes=sizes)
    print(f"wrote {windows / 'winmixar.ico'}\nwrote {windows / 'winmixarfile.ico'}")

    darwin = out / "src/release/darwin/Mixar.app/Contents/Resources"
    darwin.mkdir(parents=True, exist_ok=True)
    render_glyph(1024, margin=0.08).save(darwin / "mixar_icon.icns", format="ICNS")
    render_glyph(1024, badge="credits_slide", margin=0.08).save(
        darwin / "Mixar_Legacy_Document_Icon.icns", format="ICNS")
    print(f"wrote {darwin / 'mixar_icon.icns'}\nwrote {darwin / 'Mixar_Legacy_Document_Icon.icns'}")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=pathlib.Path, default=ROOT,
                        help="root to write under (default: this repository)")
    args = parser.parse_args(argv)
    generate(args.out.resolve())
    return 0


if __name__ == "__main__":
    sys.exit(main())
