#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Lampway contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate docs/tools.md from the LIVE tool registry (the same registry `lampway_agent_files` renders skills from, contract 04).

    python3 docs/gen_tools.py           # write docs/tools.md
    python3 docs/gen_tools.py --check   # exit 1 when docs/tools.md is stale (prints the tools added or removed)

Needs the server's dependencies importable (the server virtualenv: `server/.venv/bin/python docs/gen_tools.py`). Nothing here is hand-written
per tool: every description, input and refusal is quoted from the registry, so the page cannot drift from the code without `--check` saying so."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))

from lampway_server.agent_files import generate as G  # noqa: E402
from lampway_server.mcp import SERVER_TOOLS, offered_tools  # noqa: E402

OUT = ROOT / "docs" / "tools.md"
CONNECT = ROOT / "docs/lampway/connect-ai-apps.md"
AREA_TITLES = {
    "mesh": "Mesh, UV, rig and fit",
    "material": "Materials, textures and baking",
    "anim": "Animation, video and cameras",
    "qa": "Mesh QA and rebuild",
    "pipeline": "Pipelines, studios, ledger and assets",
    "misc": "Other",
}


def first_sentence(text: str, limit: int = 190) -> str:
    text = " ".join(str(text).split())
    m = re.match(r"(.+?\.)(\s|$)", text)
    s = m.group(1) if m else text
    return (s if len(s) <= limit else s[: limit - 1].rstrip() + "...").replace("|", "\\|")


def render() -> str:
    rows = G.registry()
    h = G.registry_hash(rows)
    offered = {t.name for t in offered_tools()}
    by_area = {}
    for r in rows:
        by_area.setdefault(G.area_of(r["name"]), []).append(r)
    n_off = sum(1 for r in rows if r["offered"])
    out = [
        "<!-- SPDX-FileCopyrightText: 2026 Lampway contributors -->",
        "<!-- SPDX-License-Identifier: GPL-3.0-or-later -->",
        f"<!-- generated by docs/gen_tools.py from registry {h}; edits are overwritten: change the tool, then regenerate -->",
        "",
        "# Tools",
        "",
        "Every tool the agent can call, quoted from the live registry. **Do not edit this file**: it is generated.",
        "",
        "```bash",
        "server/.venv/bin/python docs/gen_tools.py          # regenerate",
        "server/.venv/bin/python docs/gen_tools.py --check  # exit 1 when this page is stale",
        "```",
        "",
        f"- **{len(rows)} tools** in the agent's registry; **{n_off}** of them run in Blender and are offered over MCP, plus **{len(SERVER_TOOLS)}** server-side MCP tools "
        f"({', '.join('`' + t.name + '`' for t in SERVER_TOOLS)}): **{len(offered)} tools** over MCP in total.",
        "- Studio tools (`studio_*`) spend credits on your accounts and are **never** offered over MCP; the swarm tools and `ask_user` need the agent loop.",
        "- The `offered` column says whether an external AI app (Claude Code, Codex, Cursor, VS Code, OpenCode, Claude Desktop) can call the tool.",
        "- Every tool that costs money returns a plan and waits for your click ([spend](spend.md)); no tool can confirm a spend.",
        "- Paths a tool takes are relative to the project root; a path outside it is refused.",
        "",
        "## Index",
        "",
    ]
    for area in [a for a in AREA_TITLES if a in by_area]:
        out += [f"### {AREA_TITLES[area]}", "", "| tool | MCP | what it does |", "|---|---|---|"]
        for r in by_area[area]:
            out.append(f"| [`{r['name']}`](#{r['name'].lower()}) | {'yes' if r['offered'] else 'no'} | {first_sentence(r['description'])} |")
        out.append("")
    out += ["## Reference", "", "Each entry quotes the tool's own description and inputs.", ""]
    for area in [a for a in AREA_TITLES if a in by_area]:
        out += [f"### {AREA_TITLES[area]}", ""]
        for r in by_area[area]:
            out.append(G._tool_md(r).replace("### ", "#### ", 1).rstrip())
            out.append("")
            out.append(f"MCP: {'offered' if r['offered'] else 'not offered'}.")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_connect(text=None):
    """Update the generated count paragraph without rewriting user setup prose."""
    text = CONNECT.read_text() if text is None else text
    counts = G.registry_counts()
    paragraph = ("<!-- generated by docs/gen_tools.py: registry counts -->\n"
        f"There are **{counts['agent_tools']} tools** in the agent registry and **{counts['mcp_tools']} tools** over MCP. "
        "The MCP catalogue includes scene tools, read-only server tools and Asset Vault tools. "
        "Studio and generation tools that spend credits are **not** offered: an assistant can plan, and you confirm in the Client. "
        "The full list is generated in [tools](../tools.md). The **Connections (MCP servers)** panel in the Lampway tab "
        "shows which MCP servers each of your agent apps has and checks one on your click.")
    pattern = r'(?:<!-- generated by docs/gen_tools.py: registry counts -->\n)?(?:The server offers|There are) [^\n]+'
    out,n = re.subn(pattern, lambda _: paragraph, text)
    if n != 1: raise ValueError('connect-ai-apps must contain exactly one generated count paragraph')
    return out


def main(argv) -> int:
    outputs = {OUT: render(), CONNECT: render_connect()}
    stale = [path for path,text in outputs.items() if not path.exists() or path.read_text() != text]
    if "--check" in argv:
        if stale:
            print('Generated tool docs are stale: ' + ', '.join(str(path.relative_to(ROOT)) for path in stale) + '; run docs/gen_tools.py')
            return 1
        print('Generated tool docs are current')
        return 0
    for path,text in outputs.items():
        path.write_text(text, encoding='utf-8')
        print(f'wrote {path.relative_to(ROOT)}')
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
