# SPDX-FileCopyrightText: 2026 Lampway contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Session-file fixtures for the BYOA island view (agent-modes spec B4).

Each list is one harness's own session file, record by record, in the shape the harness writes it: Claude Code's
``~/.claude/projects/<folder>/<id>.jsonl`` and the Codex CLI's rollout ``~/.codex/sessions/YYYY/MM/DD/rollout-*.jsonl``.
They are hand-built from the record shapes the observers already read (observers/native.py) and the vendors' documented
formats; they are not copied from anyone's real files, and nothing here names a real person, path or account.
[UNVERIFIED] until each adapter's first task records a file from an installed version (spec B1).
"""
import json

CWD = "/work/demo-project"
CLAUDE_SESSION = "7f9c2ba4-0000-4000-8000-000000000001"

CLAUDE_TURNS = [
    # the harness's own preamble: metadata and a slash-command echo are not prompts
    {"type": "summary", "summary": "Demo session", "leafUuid": "u0"},
    {"type": "user", "isMeta": True, "isSidechain": False, "uuid": "m1", "sessionId": CLAUDE_SESSION, "cwd": CWD,
     "message": {"role": "user", "content": "Caveat: the messages below were generated by the user while running local commands."}},
    {"type": "user", "isSidechain": False, "uuid": "c1", "sessionId": CLAUDE_SESSION, "cwd": CWD,
     "message": {"role": "user", "content": "<command-name>/clear</command-name>"}},
    # turn 1: a prompt, a text, an MCP tool call into Lampway, its result, a shell call that fails, the answer
    {"type": "user", "isSidechain": False, "uuid": "u1", "sessionId": CLAUDE_SESSION, "cwd": CWD,
     "message": {"role": "user", "content": "Add a cube and tell me its name"}},
    {"type": "assistant", "isSidechain": False, "uuid": "a1", "sessionId": CLAUDE_SESSION,
     "message": {"id": "msg_01", "role": "assistant", "stop_reason": None,
                 "content": [{"type": "thinking", "thinking": "The scene tool can add it."}]}},
    {"type": "assistant", "isSidechain": False, "uuid": "a2", "sessionId": CLAUDE_SESSION,
     "message": {"id": "msg_01", "role": "assistant", "stop_reason": None, "content": [{"type": "text", "text": "I'll add the cube."}]}},
    {"type": "assistant", "isSidechain": False, "uuid": "a3", "sessionId": CLAUDE_SESSION,
     "message": {"id": "msg_01", "role": "assistant", "stop_reason": "tool_use",
                 "content": [{"type": "tool_use", "id": "toolu_01", "name": "mcp__lampway__lampway_scene",
                              "input": {"action": "add", "kind": "cube"}}]}},
    {"type": "user", "isSidechain": False, "uuid": "u2", "sessionId": CLAUDE_SESSION,
     "message": {"role": "user", "content": [{"type": "tool_result", "tool_use_id": "toolu_01", "is_error": False,
                                              "content": [{"type": "text", "text": "{\"ok\": true, \"created\": [\"Cube\"]}"}]}]}},
    # a subagent's records (sidechain) never reach the island
    {"type": "assistant", "isSidechain": True, "uuid": "s1", "sessionId": CLAUDE_SESSION,
     "message": {"id": "msg_side", "role": "assistant", "stop_reason": "end_turn", "content": [{"type": "text", "text": "subagent chatter"}]}},
    {"type": "assistant", "isSidechain": False, "uuid": "a4", "sessionId": CLAUDE_SESSION,
     "message": {"id": "msg_02", "role": "assistant", "stop_reason": "tool_use",
                 "content": [{"type": "tool_use", "id": "toolu_02", "name": "Bash", "input": {"command": "ls renders\nls caches"}}]}},
    {"type": "user", "isSidechain": False, "uuid": "u3", "sessionId": CLAUDE_SESSION,
     "message": {"role": "user", "content": [{"type": "tool_result", "tool_use_id": "toolu_02", "is_error": True,
                                              "content": "ls: cannot access 'renders': No such file or directory"}]}},
    {"type": "assistant", "isSidechain": False, "uuid": "a5", "sessionId": CLAUDE_SESSION,
     "message": {"id": "msg_03", "role": "assistant", "stop_reason": "end_turn",
                 "content": [{"type": "text", "text": "The cube is called Cube."}]}},
    # turn 2: a prompt the user interrupts
    {"type": "user", "isSidechain": False, "uuid": "u4", "sessionId": CLAUDE_SESSION,
     "message": {"role": "user", "content": [{"type": "text", "text": "Now bevel it"}]}},
    {"type": "assistant", "isSidechain": False, "uuid": "a6", "sessionId": CLAUDE_SESSION,
     "message": {"id": "msg_04", "role": "assistant", "stop_reason": "tool_use",
                 "content": [{"type": "tool_use", "id": "toolu_03", "name": "mcp__lampway__lampway_scene", "input": {"action": "bevel"}}]}},
    {"type": "user", "isSidechain": False, "uuid": "u5", "sessionId": CLAUDE_SESSION,
     "message": {"role": "user", "content": [{"type": "text", "text": "[Request interrupted by user for tool use]"}]}},
    # turn 3: an API error the harness reports
    {"type": "user", "isSidechain": False, "uuid": "u6", "sessionId": CLAUDE_SESSION,
     "message": {"role": "user", "content": "Try again"}},
    {"type": "system", "subtype": "api_error", "isSidechain": False, "uuid": "e1", "level": "error"},
]

CODEX_SESSION = "0199a1b2-0000-7000-8000-000000000002"

CODEX_TURNS = [
    {"timestamp": "2026-10-07T10:00:00.000Z", "type": "session_meta",
     "payload": {"id": CODEX_SESSION, "timestamp": "2026-10-07T10:00:00.000Z", "cwd": CWD, "originator": "codex_cli_rs", "cli_version": "0.0.0", "source": "cli"}},
    {"timestamp": "2026-10-07T10:00:01.000Z", "type": "response_item",
     "payload": {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "<environment_context>cwd</environment_context>"}]}},
    {"timestamp": "2026-10-07T10:00:02.000Z", "type": "event_msg", "payload": {"type": "task_started", "model_context_window": 1000}},
    {"timestamp": "2026-10-07T10:00:02.100Z", "type": "response_item",
     "payload": {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "Add a sphere"}]}},
    {"timestamp": "2026-10-07T10:00:02.200Z", "type": "event_msg", "payload": {"type": "user_message", "message": "Add a sphere", "images": []}},
    {"timestamp": "2026-10-07T10:00:03.000Z", "type": "event_msg", "payload": {"type": "agent_reasoning", "text": "thinking"}},
    {"timestamp": "2026-10-07T10:00:03.500Z", "type": "event_msg", "payload": {"type": "agent_message", "message": "Adding a sphere."}},
    {"timestamp": "2026-10-07T10:00:03.600Z", "type": "response_item",
     "payload": {"type": "message", "role": "assistant", "content": [{"type": "output_text", "text": "Adding a sphere."}]}},
    {"timestamp": "2026-10-07T10:00:04.000Z", "type": "response_item",
     "payload": {"type": "function_call", "name": "lampway__lampway_scene", "arguments": "{\"action\": \"add\", \"kind\": \"sphere\"}", "call_id": "call_1"}},
    {"timestamp": "2026-10-07T10:00:05.000Z", "type": "response_item",
     "payload": {"type": "function_call_output", "call_id": "call_1", "output": "{\"ok\": true}"}},
    {"timestamp": "2026-10-07T10:00:05.500Z", "type": "response_item",
     "payload": {"type": "function_call", "name": "shell", "arguments": "{\"command\": [\"bash\", \"-lc\", \"false\"]}", "call_id": "call_2"}},
    {"timestamp": "2026-10-07T10:00:06.000Z", "type": "response_item",
     "payload": {"type": "function_call_output", "call_id": "call_2", "output": "{\"output\": \"\", \"metadata\": {\"exit_code\": 1}}"}},
    {"timestamp": "2026-10-07T10:00:07.000Z", "type": "event_msg", "payload": {"type": "agent_message", "message": "The sphere is in."}},
    {"timestamp": "2026-10-07T10:00:07.100Z", "type": "event_msg", "payload": {"type": "token_count", "info": None}},
    {"timestamp": "2026-10-07T10:00:07.200Z", "type": "event_msg",
     "payload": {"type": "task_complete", "turn_id": "1", "last_agent_message": "The sphere is in."}},
    # a second turn the user stops
    {"timestamp": "2026-10-07T10:01:00.000Z", "type": "event_msg", "payload": {"type": "user_message", "message": "Make it red", "images": []}},
    {"timestamp": "2026-10-07T10:01:01.000Z", "type": "event_msg", "payload": {"type": "turn_aborted", "reason": "interrupted"}},
]


PI_SESSION = "1b2c3d4e-0000-4000-8000-000000000003"

#: Pi's own session file (Pi 1.0.4 docs/session-format.md, docs/message-types.md): a header, then ``message`` records. Hand-built from
#: those documented shapes (a turn needs a provider, so none was recorded from the installed copy) [UNVERIFIED by a recorded turn].
PI_TURNS = [
    {"type": "session", "version": 3, "id": PI_SESSION, "timestamp": "2026-10-07T10:00:00.000Z", "cwd": CWD},
    {"type": "message", "id": "s0000001", "parentId": None, "timestamp": "2026-10-07T10:00:00.500Z",
     "message": {"role": "system", "content": "", "sections": {"preamble": "You are an expert coding assistant"}, "timestamp": 1}},
    {"type": "message", "id": "u0000001", "parentId": "s0000001", "timestamp": "2026-10-07T10:00:01.000Z",
     "message": {"role": "user", "content": "Add a cone", "timestamp": 2}},
    {"type": "message", "id": "a0000001", "parentId": "u0000001", "timestamp": "2026-10-07T10:00:02.000Z",
     "message": {"role": "assistant", "content": [{"type": "thinking", "thinking": "the scene tool"}, {"type": "text", "text": "Adding a cone."},
                                                  {"type": "toolCall", "id": "call_1", "name": "mcp__lampway__lampway_scene",
                                                   "arguments": {"action": "add", "kind": "cone"}}],
                 "api": "x", "provider": "x", "model": "x", "usage": {}, "stopReason": "toolUse", "timestamp": 3}},
    {"type": "message", "id": "t0000001", "parentId": "a0000001", "timestamp": "2026-10-07T10:00:03.000Z",
     "message": {"role": "toolResult", "toolCallId": "call_1", "toolName": "mcp__lampway__lampway_scene",
                 "content": [{"type": "text", "text": "{\"ok\": true}"}], "isError": False, "timestamp": 4}},
    {"type": "message", "id": "a0000002", "parentId": "t0000001", "timestamp": "2026-10-07T10:00:04.000Z",
     "message": {"role": "assistant", "content": [{"type": "text", "text": "The cone is in."}], "api": "x", "provider": "x", "model": "x",
                 "usage": {}, "stopReason": "stop", "timestamp": 5}},
    {"type": "usage", "id": "g0000001", "parentId": "a0000002", "timestamp": "2026-10-07T10:00:04.100Z", "kind": "cache_warm"},
    # a second turn the user interrupts (Esc), then one the provider fails
    {"type": "message", "id": "u0000002", "parentId": "a0000002", "timestamp": "2026-10-07T10:01:00.000Z",
     "message": {"role": "user", "content": [{"type": "text", "text": "Make it red"}, {"type": "image", "data": "AAAA", "mimeType": "image/png"}],
                 "timestamp": 6}},
    {"type": "message", "id": "a0000003", "parentId": "u0000002", "timestamp": "2026-10-07T10:01:01.000Z",
     "message": {"role": "assistant", "content": [{"type": "toolCall", "id": "call_2", "name": "bash", "arguments": {"command": "ls"}}],
                 "api": "x", "provider": "x", "model": "x", "usage": {}, "stopReason": "aborted", "timestamp": 7}},
    {"type": "message", "id": "u0000003", "parentId": "a0000003", "timestamp": "2026-10-07T10:02:00.000Z",
     "message": {"role": "user", "content": "Try again", "timestamp": 8}},
    {"type": "message", "id": "a0000004", "parentId": "u0000003", "timestamp": "2026-10-07T10:02:01.000Z",
     "message": {"role": "assistant", "content": [], "api": "x", "provider": "x", "model": "x", "usage": {}, "stopReason": "error",
                 "errorMessage": "429 rate limited", "timestamp": 9}},
]


def jsonl(records) -> str:
    return "".join(json.dumps(r) + "\n" for r in records)
