"""Asset Vault video (specs/asset_library/asset_video.md section 10): clip facts, TRUE motion fps vs container fps, holds and blends, panels, derived artefacts.

Every fixture is generated by ffmpeg in the test (no download): a scrolling pattern so every real frame differs from its neighbours."""
import itertools
import json
import shutil
import subprocess

import numpy as np
import pytest
from PIL import Image

from lampway_server.library import video as V
from lampway_server.library.store import AssetLibrary, LibraryError

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None, reason="ffmpeg + ffprobe needed")
SRC = "testsrc2=size=160x120:rate={r},scroll=horizontal=0.03"


def ff(*args):
    subprocess.run(["ffmpeg", "-v", "error", "-y", *map(str, args)], check=True, timeout=120)


@pytest.fixture(scope="module")
def clips(tmp_path_factory):
    d = tmp_path_factory.mktemp("clips")
    c = {k: d / f"{k}.mp4" for k in ("plain", "dup12", "noisy12", "held5", "blend", "still", "tone", "silent", "split")}
    ff("-f", "lavfi", "-i", SRC.format(r=24), "-t", 3, "-pix_fmt", "yuv420p", c["plain"])
    ff("-f", "lavfi", "-i", SRC.format(r=12), "-t", 3, "-vf", "fps=24,format=yuv420p", c["dup12"])              # 12 fps motion in a 24 fps container
    ff("-f", "lavfi", "-i", SRC.format(r=12), "-t", 3, "-vf", "fps=24,noise=alls=12:allf=t,format=yuv420p", c["noisy12"])   # held frames differ by grain, not by motion
    ff("-f", "lavfi", "-i", SRC.format(r="24/5"), "-t", 3, "-vf", "fps=24,format=yuv420p", c["held5"])          # each picture shown five times: 4.8 fps
    ff("-f", "lavfi", "-i", SRC.format(r=12), "-t", 3, "-vf", "minterpolate=fps=24:mi_mode=blend,format=yuv420p", c["blend"])
    png = d / "still.png"
    Image.fromarray(np.random.default_rng(1).integers(0, 255, (120, 160, 3), dtype=np.uint8)).save(png)
    ff("-loop", 1, "-framerate", 24, "-i", png, "-t", 2, "-pix_fmt", "yuv420p", c["still"])
    ff("-f", "lavfi", "-i", SRC.format(r=24), "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000", "-t", 2, "-pix_fmt", "yuv420p", "-shortest", c["tone"])
    ff("-f", "lavfi", "-i", SRC.format(r=24), "-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo", "-t", 2, "-pix_fmt", "yuv420p", "-shortest", c["silent"])
    ff("-f", "lavfi", "-i", SRC.format(r=24), "-f", "lavfi", "-i", "color=black:size=8x120:rate=24", "-f", "lavfi", "-i", "mandelbrot=size=160x120:rate=24",
       "-t", 2, "-filter_complex", "[0][1][2]hstack=inputs=3,format=yuv420p", c["split"])
    return c


def make_lib(tmp_path):
    ids, clock = itertools.count(1), itertools.count(1000)
    return AssetLibrary(tmp_path / "lib", idgen=lambda: f"id{next(ids):05d}", clock=lambda: float(next(clock)))


def put(lib, path, kind="video", name=None):
    return lib.put({"kind": kind, "name": name or path.stem, "source": {"kind": "t", "key": str(path)}, "files": [{"role": "main", "path": str(path), "storage": "external"}]})["id"]


# 1 -------------------------------------------------------------------------------------------------------------------------------
def test_probe_matches_ffprobe_for_every_fixture(clips):
    for name, path in clips.items():
        p = V.probe(path)
        raw = json.loads(subprocess.run(["ffprobe", "-v", "error", "-show_format", "-show_streams", "-of", "json", str(path)], capture_output=True, text=True).stdout)
        vs = next(s for s in raw["streams"] if s["codec_type"] == "video")
        assert (p["codec"], p["width"], p["height"], p["pix_fmt"]) == (vs["codec_name"], vs["width"], vs["height"], vs["pix_fmt"]), name
        assert p["container_fps"] == pytest.approx(24.0) and p["duration_s"] == pytest.approx(float(raw["format"]["duration"]))
        assert p["frame_count"] > 0                                                          # counted by decoding when the container does not say
        assert p["has_audio"] == (1 if name in ("tone", "silent") else 0), name


# 2 / 3 / 4 -----------------------------------------------------------------------------------------------------------------------
def test_motion_fps_of_duplicated_clip_is_12_not_24(clips):
    plain, dup, held = (V.analyze_motion(clips[k], 24.0) for k in ("plain", "dup12", "held5"))
    assert plain["motion_fps"] == pytest.approx(24.0, abs=0.3) and plain["dup_frames"] == 0 and plain["blend_suspect"] == 0
    assert dup["motion_fps"] == pytest.approx(12.0, abs=0.3) and dup["dup_ratio"] == pytest.approx(0.5, abs=0.05) and dup["longest_hold"] == 1
    assert held["motion_fps"] == pytest.approx(4.8, abs=0.3) and held["longest_hold"] == 4
    assert dup["motion_fps_confidence"] > 0.8


def test_a_held_frame_under_grain_is_still_a_hold(clips):
    """Grain makes every held frame differ a little (about 2 grey levels here) while motion moves about 24: the threshold adapts to the clip, a fixed floor would read 24 fps."""
    n = V.analyze_motion(clips["noisy12"], 24.0)
    assert n["motion_fps"] == pytest.approx(12.0, abs=0.3) and n["dup_ratio"] == pytest.approx(0.5, abs=0.05)


def test_blend_clip_is_flagged_not_misreported(clips):
    b = V.analyze_motion(clips["blend"], 24.0)
    assert b["blend_suspect"] == 1 and b["motion_fps"] is None                                # never "24": the inbetweens are blends of their neighbours


def test_still_clip_has_motion_energy_zero_and_dup_ratio_one(clips):
    s = V.analyze_motion(clips["still"], 24.0)
    assert s["dup_ratio"] == 1.0 and s["motion_energy"] == pytest.approx(0.0, abs=0.05) and s["motion_fps"] == 0.0


# 5 -------------------------------------------------------------------------------------------------------------------------------
def test_split_detector_finds_the_divider_and_rects_sum_to_frame(clips):
    sp = V.detect_panels(clips["split"])
    assert sp["panel_layout"] == "split_front_side"
    rects = sp["panels"]
    assert len(rects) == 2 and rects[0]["x"] == 0 and rects[1]["x"] + rects[1]["w"] == 328
    assert 155 <= rects[0]["w"] <= 165 and sum(r["w"] for r in rects) + sp["divider"]["w"] == 328 and all(r["h"] == 120 for r in rects)
    assert V.detect_panels(clips["plain"])["panel_layout"] == "single"


def test_a_one_pixel_line_on_flat_grey_is_the_divider_not_the_empty_background(tmp_path):
    """The shape of a real split render: two figures on one flat grey, a thin darker line between them, and empty grey either side of it (29 px: under the
    10 % width cap, so the tone contrast, not the cap, is what rejects it)."""
    out = tmp_path / "line.mp4"
    ff("-f", "lavfi", "-i", "color=c=0x7b7b7b:s=320x120:r=24", "-f", "lavfi", "-i", "testsrc2=s=60x60:r=24", "-f", "lavfi", "-i", "testsrc2=s=60x60:r=24", "-t", 2,
       "-filter_complex", "[0][1]overlay=70:30[t];[t][2]overlay=191:30,drawbox=x=159:y=0:w=2:h=120:color=0x5f5f5f:t=fill,format=yuv420p", out)
    sp = V.detect_panels(out)
    assert sp["panel_layout"] == "split_front_side" and 157 <= sp["divider"]["x"] <= 160 and sp["divider"]["w"] <= 4, sp


# 6 -------------------------------------------------------------------------------------------------------------------------------
def test_derived_artefacts_link_with_the_right_relations(clips, tmp_path):
    lib = make_lib(tmp_path)
    clip = put(lib, clips["plain"])
    out = V.derive(lib, clip, ["frame_strip", "proxy", "keyframes"], strip={"count": 8, "size": 128})
    strip = out["frame_strip"]["asset_id"]
    a = lib.get(strip)
    assert a["kind"] == "image" and a["subtype"] == "strip"
    assert {"src": strip, "dst": clip, "type": "derived_from", "role": "frame_strip", "by": "rule"} in a["relations"]
    assert out["proxy"]["frames"] == 24 and all(f["role"] == "proxy" for f in lib.get(clip)["files"] if f["role"] == "proxy")
    kf = lib._reader().execute("select count(*) from embedding where space='video_kf_hist' and sub_key like 'kf:%'").fetchone()[0]
    assert 1 <= kf <= 24
    png = tmp_path / "start.png"
    Image.new("RGB", (16, 16), (9, 9, 9)).save(png)
    anim = tmp_path / "walk.json"
    anim.write_text("{}")
    start = V.attach(lib, clip, png, "start_frame")
    walk = V.attach(lib, clip, anim, "retargeted")
    rels = lib.get(clip)["relations"]
    assert {"src": clip, "dst": start, "type": "generated_from", "role": "start_frame", "by": "rule"} in rels
    assert {"src": clip, "dst": walk, "type": "drives", "role": "", "by": "rule"} in rels and lib.get(walk)["kind"] == "animation"
    with pytest.raises(LibraryError, match="tell me the layout"):
        V.derive(lib, clip, ["split_panels"])


def test_split_panels_become_part_of_the_clip(clips, tmp_path):
    lib = make_lib(tmp_path)
    clip = put(lib, clips["split"])
    V.analyze(lib, clip)
    out = V.derive(lib, clip, ["split_panels"])
    parts = out["split_panels"]["asset_ids"]
    assert len(parts) == 2
    for pid, role in zip(parts, ("panel:front", "panel:side")):
        a = lib.get(pid)
        assert a["kind"] == "video" and a["subtype"] == "split"
        assert {"src": pid, "dst": clip, "type": "part_of", "role": role, "by": "rule"} in a["relations"]
        assert V.probe(a["files"][0]["locations"][0]["path"])["width"] == 160


# 7 -------------------------------------------------------------------------------------------------------------------------------
def test_has_audio_and_silent_audio_distinguished(clips):
    assert V.audio_facts(clips["tone"]) == {"has_audio": 1, "audio_codec": "aac", "audio_silent": 0}
    assert V.audio_facts(clips["silent"])["audio_silent"] == 1
    assert V.audio_facts(clips["plain"]) == {"has_audio": 0, "audio_codec": None, "audio_silent": None}


# 8 -------------------------------------------------------------------------------------------------------------------------------
def test_analysis_is_reproducible_and_lands_in_video_stats_and_gates(clips, tmp_path):
    lib = make_lib(tmp_path)
    clip = put(lib, clips["dup12"])
    a, b = V.analyze(lib, clip), V.analyze(lib, clip)
    assert json.dumps(a["stats"], sort_keys=True) == json.dumps(b["stats"], sort_keys=True)
    st = lib.get(clip)["stats"]
    assert st["motion_fps"] == pytest.approx(12.0, abs=0.3) and st["container_fps"] == 24.0 and st["analyzed_with"].startswith("lampway.video@")
    assert len(lib.get(clip)["gates"]) == 3                                         # a re-analysis replaces its gate rows, never piles them up
    gates = {g["gate"]: g for g in lib.get(clip)["gates"]}
    assert gates["motion_fps_ge_24"]["passed"] == 0 and gates["dup_frames"]["value"] > 0
    row = lib._reader().execute("select motion_fps,dup_ratio from v_video_clips where id=?", (clip,)).fetchone()
    assert row[0] == pytest.approx(12.0, abs=0.3)


def test_refusals_name_the_fix(clips, tmp_path, monkeypatch):
    lib = make_lib(tmp_path)
    png = tmp_path / "p.png"
    Image.new("RGB", (8, 8)).save(png)
    img = put(lib, png, kind="image")
    with pytest.raises(LibraryError, match="not a video: kind is image"):
        V.analyze(lib, img)
    bad = tmp_path / "bad.mp4"
    bad.write_bytes(b"\x00\x00\x00\x18ftypmp42" + b"\x00" * 64)
    broken = put(lib, bad)
    with pytest.raises(LibraryError, match="cannot decode"):
        V.analyze(lib, broken)
    assert "defect:undecodable" in lib.get(broken)["tags"] and lib.get(broken)["status"] == "active"
    clip = put(lib, clips["plain"])
    monkeypatch.setattr(V, "MAX_ANALYZE_S", 1.0)
    with pytest.raises(LibraryError, match="clip longer than 1 s: analyse a range: pass start_s/end_s"):
        V.analyze(lib, clip)
    assert V.analyze(lib, clip, start_s=0.5, end_s=1.4)["stats"]["frame_count"] > 0
    monkeypatch.setattr(V.shutil, "which", lambda n: None)
    with pytest.raises(LibraryError, match="ffmpeg not found on PATH"):
        V.probe(clips["plain"])


# 9 -------------------------------------------------------------------------------------------------------------------------------
def test_compare_alignment_lengths_match(clips, tmp_path):
    lib = make_lib(tmp_path)
    a, b = put(lib, clips["plain"]), put(lib, clips["dup12"])
    for align in ("start", "time", "motion"):
        out = V.compare(lib, a, b, align=align)
        assert len(out["a"]) == len(out["b"]) > 0, align
        assert out["a"] == sorted(out["a"]) and out["b"] == sorted(out["b"])          # monotone: a side-by-side never runs backwards


def test_the_tool_surface_returns_ok_or_a_refusal_with_help(clips, tmp_path):
    lib = make_lib(tmp_path)
    clip = put(lib, clips["held5"])
    out = V.handle(lib, {"action": "analyze", "asset_id": clip})
    assert out["ok"] is True and out["stats"]["motion_fps"] == pytest.approx(4.8, abs=0.3)
    bad = V.handle(lib, {"action": "strip", "asset_id": clip, "strip": {"count": 500}})
    assert bad["ok"] is False and "count 8..64" in bad["error"] and bad["help"]
