"""Facelift contract 10: the cockpit window's page (the zero-install fallback beside contract 16's WezTerm). The page and
its assets are static and come only from the server's origin; the data comes from /app/workbench/view behind the bearer;
the colours are the tokens; a restart's reconcile is said in one sentence; a pane Lampway did not create offers nothing
to type into and nothing to stop; and the report cards mount in it (mrmak 09's Workbench frame)."""
import json
import re
from pathlib import Path

import pytest
from starlette.testclient import TestClient

from lampway_server import workbench_view as WV
from lampway_server.app import create_app
from lampway_server.herdr.host import Cockpit

from .herdr_support import lroot  # noqa: F401

ROOT = Path(__file__).resolve().parents[2]
PAGE = ROOT / "server/lampway_server/web/workbench"
TOKENS = json.loads((ROOT / "scripts/lampway/facelift/theme/tokens.json").read_text(encoding="utf-8"))["colour"]


@pytest.fixture
def stack(settings, provider, lroot, tmp_path, monkeypatch):  # noqa: F811
    monkeypatch.setenv("LAMPWAY_PROJECT_ROOT", str(tmp_path))
    app = create_app(settings, provider=provider, cockpit=Cockpit(lroot, project_root=str(tmp_path)))
    with TestClient(app, base_url="http://127.0.0.1:8787") as http:
        from .fake_client import FakeMixarClient
        fake = FakeMixarClient(http, password=settings.user_password)
        fake.login()
        yield http, fake


def test_tokens_css_matches_tokens_json():
    css = (PAGE / "tokens.css").read_text(encoding="utf-8")
    found = dict(re.findall(r"--lw-([a-z_]+):\s*(#[0-9a-fA-F]{6})", css))
    assert found == {name: v["dark"].lower() for name, v in TOKENS.items()} or {k: v.lower() for k, v in found.items()} == \
        {name: v["dark"].lower() for name, v in TOKENS.items()}, found
    assert "GENERATED by scripts/lampway/facelift/theme/build_theme.py" in css


def test_reconcile_banner_text():
    rec = {"adopted": ["a", "b", "c", "d"], "unadopted": ["p9"], "ended": []}
    banner = WV.banner(rec)
    assert banner["text"] == "4 sessions re-adopted with their state. 1 pane is not ours: left running, never typed into."
    assert banner["tooltip"].endswith("Nothing was restarted, nothing was killed.")
    assert WV.banner({"adopted": ["a"], "unadopted": [], "ended": []})["text"] == "1 session re-adopted with its state."
    assert WV.banner(None) is None


def test_unadopted_row_has_no_type_or_stop_control():
    view = WV.view({"server": {"running": True}, "sessions": [{"id": "s1", "name": "Lantern", "agent": "claude", "cwd": "/p", "state": "live",
                                                               "adopted": True, "agent_sends": False, "activity": "working"}]},
                   {"adopted": ["s1"], "unadopted": ["p9"], "ended": []})
    rows = {r["id"]: r for r in view["rows"]}
    assert rows["s1"]["can_type"] and rows["s1"]["can_stop"] and rows["s1"]["spark"] == "working"
    assert rows["p9"]["adopted"] is False and rows["p9"]["can_type"] is False and rows["p9"]["can_stop"] is False
    js = (PAGE / "cockpit.js").read_text(encoding="utf-8")
    assert "row.can_type" in js and "row.can_stop" in js, "the page draws the input and Stop only where the view allows them"


def test_agent_sends_switch_defaults_off():
    view = WV.view({"server": {"running": True}, "sessions": [{"id": "s1", "name": "n", "agent": "codex", "cwd": "/p", "state": "live"}]}, None)
    assert view["rows"][0]["agent_sends"] is False


def test_page_makes_no_third_party_request(stack):
    http, fake = stack
    page = http.get("/app/workbench/page")
    assert page.status_code == 200 and "text/html" in page.headers["content-type"]
    csp = page.headers.get("content-security-policy", "")
    assert "default-src 'self'" in csp and "connect-src 'self'" in csp
    for name in ("index.html", "cockpit.js", "cockpit.css", "tokens.css"):
        text = (PAGE / name).read_text(encoding="utf-8")
        for url in re.findall(r"(?:https?:)?//[^\s\"')]+", text):
            assert re.match(r"(?:https?:)?//(127\.0\.0\.1|localhost)[:/]", url), (name, url)
    for name in ("cockpit.js", "cockpit.css", "tokens.css"):
        assert http.get(f"/app/workbench/static/{name}").status_code == 200
    assert http.get("/app/workbench/static/../app.py").status_code == 404
    assert http.get("/app/workbench/static/secret.txt").status_code == 404


def test_the_view_needs_the_bearer_and_mounts_the_report_cards(stack):
    http, fake = stack
    assert http.get("/app/workbench/view").status_code == 401
    view = http.get("/app/workbench/view", headers=fake.rest_headers()).json()
    assert view["server"]["running"] is False and view["rows"] == [] and view["banner"] is None
    js = (PAGE / "cockpit.js").read_text(encoding="utf-8")
    assert "/app/cards" in js and "/open" in js, "the report cards mount in the window (mrmak 09's Workbench frame)"
    html = (PAGE / "index.html").read_text(encoding="utf-8")
    assert 'id="cards"' in html


def test_the_page_offers_the_lampway_terminal():
    """Contract 10's terminal is contract 16's window: the page asks /app/terminal and offers Open when it is installed, Get
    otherwise; the browser pane stays the zero-install fallback."""
    js = (PAGE / "cockpit.js").read_text(encoding="utf-8")
    assert "/app/terminal" in js and "/app/terminal/open" in js and "Open in the Lampway terminal" in js
    assert 'id="terminal"' in (PAGE / "index.html").read_text(encoding="utf-8")
