"""The job queue's provenance hook: a finished (or failed) generation lands in the Vault with its origin; a hook failure never fails the job."""
import itertools
import json

import pytest

from lampway_server.jobqueue import ImageOutput, JobQueue
from lampway_server.library import hooks as H
from lampway_server.library.store import AssetLibrary

pytestmark = pytest.mark.anyio

PNG = b"\x89PNG\r\n\x1a\n" + b"\x00" * 32


class Hub:
    sockets = {}


def make_lib(tmp_path):
    ids, clock = itertools.count(1), itertools.count(1000)
    return AssetLibrary(tmp_path / "lib", idgen=lambda: f"id{next(ids):05d}", clock=lambda: float(next(clock)))


def backend(fail=False):
    def run(model, payload):
        if fail:
            raise RuntimeError("the image model is down")
        return ImageOutput(images=[(PNG, "image/png")], image_name="")
    return run


async def test_a_finished_image_job_is_captured_with_its_origin(tmp_path):
    lib = make_lib(tmp_path)
    q = JobQueue({"image_gen": backend()}, Hub(), "http://127.0.0.1:1", provenance=H.job_hook(lib, tmp_path / "spool.jsonl"))
    job = q.submit("image_gen", "openai/gpt-image-2.5", {"prompt": "a brass lamp"})
    await job.task
    assert job.status == "DONE"
    img = [r[0] for r in lib._db.execute("select id from asset where kind='image'")]
    assert len(img) == 1
    g = lib.get(img[0])["generation"][0]
    assert (g["action"], g["model"], g["job_id"], g["prompt_text"], g["cost_basis"]) == ("image_gen", "openai/gpt-image-2.5", job.job_id, "a brass lamp", "none")
    assert lib.get(img[0])["files"][0]["locations"][0]["storage"] == "cas"


async def test_a_failed_job_is_a_cost_worth_querying_and_creates_no_image(tmp_path):
    lib = make_lib(tmp_path)
    q = JobQueue({"image_gen": backend(fail=True)}, Hub(), "http://127.0.0.1:1", provenance=H.job_hook(lib, tmp_path / "spool.jsonl"))
    job = q.submit("image_gen", "m", {"prompt": "x"})
    await job.task
    assert job.status == "FAILED" and "image" not in lib.status()["assets"]["by_kind"]
    row = lib._db.execute("select action,job_id,params_json from generation").fetchone()
    assert row[0] == "image_gen" and row[1] == job.job_id and json.loads(row[2])["ok"] is False and "the image model is down" in json.loads(row[2])["error"]


async def test_a_hook_that_raises_cannot_fail_the_job(tmp_path):
    def boom(job, ok, provider):
        raise RuntimeError("provenance exploded")
    q = JobQueue({"image_gen": backend()}, Hub(), "http://127.0.0.1:1", provenance=boom)
    job = q.submit("image_gen", "m", {"prompt": "x"})
    await job.task
    assert job.status == "DONE" and job.result["images"]


async def test_with_the_library_closed_the_record_is_spooled(tmp_path):
    spool = tmp_path / "spool.jsonl"
    q = JobQueue({"image_gen": backend()}, Hub(), "http://127.0.0.1:1", provenance=H.job_hook(None, spool))
    job = q.submit("image_gen", "m", {"prompt": "x"})
    await job.task
    assert job.status == "DONE" and len(spool.read_text().splitlines()) == 1
    blobs = list((tmp_path / "spool_blobs").iterdir())
    assert len(blobs) == 1 and blobs[0].read_bytes() == PNG                          # the generated bytes are the only copy: they are kept, not dropped


async def test_a_spooled_generation_is_replayed_into_the_library_when_it_opens(tmp_path):
    from lampway_server.library import provenance as P
    spool = tmp_path / "spool.jsonl"
    q = JobQueue({"image_gen": backend()}, Hub(), "http://127.0.0.1:1", provenance=H.job_hook(None, spool))
    job = q.submit("image_gen", "m", {"prompt": "x"})
    await job.task
    lib = make_lib(tmp_path)
    assert P.replay_spool(lib, spool) == {"replayed": 1, "still_failing": 0}
    assert lib.status()["assets"]["by_kind"]["image"] == 1 and not list((tmp_path / "spool_blobs").iterdir())
